#!/usr/bin/env python3
"""Merge extra titles into catalog.json and download missing posters."""

from __future__ import annotations

import json
import time
import urllib.error
import urllib.parse
import urllib.request
from pathlib import Path

UA = "OpenShelf/0.1 (educational OTT catalog; https://localhost)"
CATALOG = Path(__file__).resolve().parent / "data" / "catalog.json"
PUBLIC = Path(__file__).resolve().parents[2] / "frontend" / "public"
POSTERS = PUBLIC / "posters"
BACKDROPS = PUBLIC / "backdrops"

# wiki is Wikipedia REST title, stripped before save.
ADDITIONS: list[dict] = [
    dict(id="mirzapur", title="Mirzapur", year=2018, type="series", seasons=3, genres=["Crime", "Thriller", "Drama", "Action"], languages=["Hindi"], countries=["India"], imdb=8.5, overview="A carpet-business family in Uttar Pradesh is pulled into the state's gun-and-politics underworld.", themes=["underworld", "family", "power"], directors=["Karan Anshuman"], platforms=["Prime Video"], poster_hue=18, wiki="Mirzapur_(TV_series)"),
    dict(id="scam-1992", title="Scam 1992", year=2020, type="series", seasons=1, genres=["Crime", "Drama", "Biography"], languages=["Hindi"], countries=["India"], imdb=9.3, overview="Harshad Mehta's rise and the 1992 securities scam that shook Bombay.", themes=["finance", "ambition", "true story"], directors=["Hansal Mehta"], platforms=["SonyLIV"], poster_hue=32, wiki="Scam_1992"),
    dict(id="panchayat", title="Panchayat", year=2020, type="series", seasons=3, genres=["Comedy", "Drama"], languages=["Hindi"], countries=["India"], imdb=8.9, overview="An engineering graduate takes a panchayat secretary job in a remote village.", themes=["village", "bureaucracy", "coming of age"], directors=["Deepak Kumar Mishra"], platforms=["Prime Video"], poster_hue=95, wiki="Panchayat_(TV_series)"),
    dict(id="asur", title="Asur", year=2020, type="series", seasons=2, genres=["Crime", "Thriller", "Mystery"], languages=["Hindi"], countries=["India"], imdb=8.5, overview="A forensic officer hunts a ritual killer who hides behind mythology.", themes=["serial killer", "mythology", "forensics"], directors=["Onir"], platforms=["JioHotstar"], poster_hue=0, wiki="Asur_(TV_series)"),
    dict(id="farzi", title="Farzi", year=2023, type="series", seasons=1, genres=["Crime", "Thriller", "Drama"], languages=["Hindi"], countries=["India"], imdb=8.3, overview="An artist is pulled into a counterfeit-currency network.", themes=["counterfeit", "art", "crime"], directors=["Raj Nidimoru", "Krishna D.K."], platforms=["Prime Video"], poster_hue=12, wiki="Farzi"),
    dict(id="jamtara", title="Jamtara", year=2020, type="series", seasons=2, genres=["Crime", "Drama", "Thriller"], languages=["Hindi"], countries=["India"], imdb=7.3, overview="Teen phishing gangs in a Jharkhand town draw the cyber-crime police.", themes=["phishing", "youth", "true crime"], directors=["Soumendra Padhi"], platforms=["Netflix"], poster_hue=28, wiki="Jamtara_(TV_series)"),
    dict(id="rocket-boys", title="Rocket Boys", year=2022, type="series", seasons=2, genres=["Biography", "Drama", "History"], languages=["Hindi"], countries=["India"], imdb=8.9, overview="Homes and Sarabhai build India's space and nuclear programmes.", themes=["science", "nation", "friendship"], directors=["Abhay Purohit"], platforms=["SonyLIV"], poster_hue=210, wiki="Rocket_Boys"),
    dict(id="khakee-bihar", title="Khakee: The Bihar Chapter", year=2022, type="series", seasons=1, genres=["Crime", "Thriller", "Drama"], languages=["Hindi"], countries=["India"], imdb=7.4, overview="A Bihar cop takes on a gangster while the system works against him.", themes=["police", "corruption", "bihar"], directors=["Bhav Dhulia"], platforms=["Netflix"], poster_hue=22, wiki="Khakee:_The_Bihar_Chapter"),
    dict(id="gullak", title="Gullak", year=2019, type="series", seasons=4, genres=["Comedy", "Drama", "Family"], languages=["Hindi"], countries=["India"], imdb=9.1, overview="A middle-class family in a small North Indian town lives on tea, exams, and small crises.", themes=["family", "middle class"], directors=["Palash Vaswani"], platforms=["SonyLIV"], poster_hue=30, wiki="Gullak"),
    dict(id="kota-factory", title="Kota Factory", year=2019, type="series", seasons=3, genres=["Drama", "Comedy"], languages=["Hindi"], countries=["India"], imdb=9.0, overview="IIT-JEE factory towns and the kids who live inside them.", themes=["exams", "friendship", "pressure"], directors=["Raghav Subbu"], platforms=["Netflix"], poster_hue=200, wiki="Kota_Factory"),
    dict(id="tvf-pitchers", title="Pitchers", year=2015, type="series", seasons=2, genres=["Drama", "Comedy"], languages=["Hindi"], countries=["India"], imdb=9.1, overview="Four friends try to build a startup out of a Gurugram flat.", themes=["startup", "friendship"], directors=["Amit Golani"], platforms=["Prime Video", "TVF"], poster_hue=18, wiki="TVF_Pitchers"),
    dict(id="gangs-wasseypur", title="Gangs of Wasseypur", year=2012, runtime_min=160, genres=["Crime", "Action", "Thriller", "Drama"], languages=["Hindi"], countries=["India"], imdb=8.2, overview="A coal-town vendetta spanning decades in Dhanbad.", themes=["revenge", "coal", "saga"], directors=["Anurag Kashyap"], platforms=["Netflix", "Prime Video"], poster_hue=20, wiki="Gangs_of_Wasseypur"),
    dict(id="tumbbad", title="Tumbbad", year=2018, runtime_min=104, genres=["Horror", "Fantasy", "Drama"], languages=["Hindi"], countries=["India"], imdb=8.2, overview="A village curse and a god of greed in colonial Maharashtra.", themes=["greed", "folklore", "rain"], directors=["Rahi Anil Barve"], platforms=["Netflix", "Prime Video"], poster_hue=25, wiki="Tumbbad"),
    dict(id="article-15", title="Article 15", year=2019, runtime_min=130, genres=["Crime", "Drama", "Thriller"], languages=["Hindi"], countries=["India"], imdb=8.1, overview="A cop investigates missing girls and caste violence in rural UP.", themes=["caste", "police", "justice"], directors=["Anubhav Sinha"], platforms=["Netflix", "Prime Video"], poster_hue=40, wiki="Article_15_(film)"),
    dict(id="pink-2016", title="Pink", year=2016, runtime_min=136, genres=["Drama", "Crime", "Thriller"], languages=["Hindi"], countries=["India"], imdb=8.1, overview="Three women and a retired lawyer fight a consent case in Delhi.", themes=["consent", "courtroom"], directors=["Aniruddha Roy Chowdhury"], platforms=["Prime Video"], poster_hue=330, wiki="Pink_(2016_film)"),
    dict(id="12th-fail", title="12th Fail", year=2023, runtime_min=147, genres=["Drama", "Biography"], languages=["Hindi"], countries=["India"], imdb=8.8, overview="A UP student keeps sitting the UPSC after a ruined board exam.", themes=["exams", "perseverance"], directors=["Vidhu Vinod Chopra"], platforms=["JioHotstar"], poster_hue=28, wiki="12th_Fail"),
    dict(id="laapataa-ladies", title="Laapataa Ladies", year=2023, runtime_min=122, genres=["Comedy", "Drama"], languages=["Hindi"], countries=["India"], imdb=8.0, overview="Two brides are swapped on a train and a station master has to sort it out.", themes=["identity", "village", "women"], directors=["Kiran Rao"], platforms=["Netflix"], poster_hue=15, wiki="Laapataa_Ladies"),
    dict(id="the-lunchbox", title="The Lunchbox", year=2013, runtime_min=104, genres=["Drama", "Romance"], languages=["Hindi"], countries=["India"], imdb=7.8, overview="A mistaken dabbawala delivery starts letters between strangers in Mumbai.", themes=["letters", "loneliness", "city"], directors=["Ritesh Batra"], platforms=["Netflix", "Prime Video"], poster_hue=22, wiki="The_Lunchbox"),
    dict(id="masaan", title="Masaan", year=2015, runtime_min=109, genres=["Drama", "Romance"], languages=["Hindi"], countries=["India"], imdb=8.1, overview="Two stories of shame and grace on the ghats of Banaras.", themes=["grief", "caste", "ghat"], directors=["Neeraj Ghaywan"], platforms=["Netflix"], poster_hue=30, wiki="Masaan"),
    dict(id="queen-2013", title="Queen", year=2013, runtime_min=146, genres=["Comedy", "Drama"], languages=["Hindi"], countries=["India"], imdb=8.1, overview="A dumped bride takes her honeymoon to Paris and Amsterdam alone.", themes=["self discovery", "travel"], directors=["Vikas Bahl"], platforms=["Netflix", "Prime Video"], poster_hue=340, wiki="Queen_(2014_film)"),
    dict(id="kgf-2", title="K.G.F: Chapter 2", year=2022, runtime_min=168, genres=["Action", "Crime", "Drama"], languages=["Kannada"], countries=["India"], imdb=8.2, overview="Rocky takes the Kolar gold fields and the government comes for him.", themes=["rise", "gold", "power"], directors=["Prashanth Neel"], platforms=["Prime Video", "Netflix"], poster_hue=8, wiki="KGF:_Chapter_2"),
    dict(id="kantara", title="Kantara", year=2022, runtime_min=148, genres=["Action", "Drama", "Thriller", "Fantasy"], languages=["Kannada"], countries=["India"], imdb=8.2, overview="A Kambala star clashes with a forest officer over land, gods, and a daiva.", themes=["folklore", "land", "possession"], directors=["Rishab Shetty"], platforms=["Prime Video", "Netflix"], poster_hue=35, wiki="Kantara_(film)"),
    dict(id="rrr", title="RRR", year=2022, runtime_min=187, genres=["Action", "Drama", "History"], languages=["Telugu"], countries=["India"], imdb=7.8, overview="Two revolutionaries in 1920s Delhi become friends under the Raj.", themes=["friendship", "colonial", "dance"], directors=["S. S. Rajamouli"], platforms=["Netflix"], poster_hue=5, wiki="RRR_(film)"),
    dict(id="baahubali-2", title="Baahubali 2: The Conclusion", year=2017, runtime_min=167, genres=["Action", "Drama", "Fantasy"], languages=["Telugu"], countries=["India"], imdb=8.2, overview="Mahishmati's secret of why Kattappa killed Baahubali.", themes=["kingdom", "betrayal"], directors=["S. S. Rajamouli"], platforms=["Netflix", "Prime Video"], poster_hue=40, wiki="Baahubali_2:_The_Conclusion"),
    dict(id="pushpa", title="Pushpa: The Rise", year=2021, runtime_min=179, genres=["Action", "Crime", "Drama"], languages=["Telugu"], countries=["India"], imdb=7.6, overview="A labourer rises through the red-sandalwood smuggling belt.", themes=["smuggling", "rise", "machismo"], directors=["Sukumar"], platforms=["Prime Video", "Netflix"], poster_hue=10, wiki="Pushpa:_The_Rise"),
    dict(id="salaar", title="Salaar: Part 1 – Ceasefire", year=2023, runtime_min=175, genres=["Action", "Crime", "Drama"], languages=["Telugu"], countries=["India"], imdb=6.5, overview="A feared enforcer returns to a fictional city-state of gangs.", themes=["loyalty", "exile"], directors=["Prashanth Neel"], platforms=["Netflix"], poster_hue=0, wiki="Salaar:_Part_1_–_Ceasefire"),
    dict(id="vikram-vedha-2017", title="Vikram Vedha", year=2017, runtime_min=147, genres=["Action", "Crime", "Thriller"], languages=["Tamil"], countries=["India"], imdb=8.2, overview="A cop and a gangster tell competing versions of the same killings.", themes=["unreliable", "cat and mouse"], directors=["Pushkar–Gayathri"], platforms=["Prime Video", "Netflix"], poster_hue=15, wiki="Vikram_Vedha"),
    dict(id="vikram-vedha-2022", title="Vikram Vedha", year=2022, runtime_min=160, genres=["Action", "Crime", "Thriller"], languages=["Hindi"], countries=["India"], imdb=7.1, overview="Hindi remake of the Tamil cop-versus-gangster fable.", themes=["unreliable", "remake"], directors=["Pushkar–Gayathri"], platforms=["Prime Video", "Netflix"], poster_hue=16, tags=["Remake"], remake_of="Vikram Vedha (2017, Tamil)", wiki="Vikram_Vedha_(2022_film)"),
    dict(id="ratsasan", title="Ratsasan", year=2018, runtime_min=170, genres=["Crime", "Thriller", "Mystery", "Horror"], languages=["Tamil"], countries=["India"], imdb=8.3, overview="A wannabe filmmaker turned cop hunts a serial killer of schoolgirls.", themes=["serial killer", "investigation"], directors=["Ram Kumar"], platforms=["Netflix", "Prime Video"], poster_hue=0, wiki="Ratsasan"),
    dict(id="soorarai-pottru", title="Soorarai Pottru", year=2020, runtime_min=153, genres=["Drama", "Action", "Biography"], languages=["Tamil"], countries=["India"], imdb=8.7, overview="A former IAF officer tries to launch a low-cost airline.", themes=["aviation", "underdog"], directors=["Sudha Kongara"], platforms=["Prime Video", "Netflix"], poster_hue=200, wiki="Soorarai_Pottru"),
    dict(id="96-film", title="96", year=2018, runtime_min=158, genres=["Drama", "Romance"], languages=["Tamil"], countries=["India"], imdb=8.5, overview="Two school sweethearts meet again at a reunion after 22 years.", themes=["memory", "reunion", "what if"], directors=["C. Prem Kumar"], platforms=["Prime Video"], poster_hue=20, wiki="96_(film)"),
    dict(id="ponniyin-selvan-1", title="Ponniyin Selvan: I", year=2022, runtime_min=167, genres=["Action", "Drama", "History"], languages=["Tamil"], countries=["India"], imdb=7.6, overview="Chola succession plots, spies, and a prince across the sea.", themes=["empire", "intrigue"], directors=["Mani Ratnam"], platforms=["Prime Video", "Netflix"], poster_hue=32, wiki="Ponniyin_Selvan:_I"),
    dict(id="aavesham", title="Aavesham", year=2024, runtime_min=163, genres=["Action", "Comedy", "Crime"], languages=["Malayalam"], countries=["India"], imdb=7.9, overview="Three Bengaluru students hire a gangster to settle a college fight.", themes=["gangster", "comedy", "campus"], directors=["Jithu Madhavan"], platforms=["Prime Video", "JioHotstar"], poster_hue=8, wiki="Aavesham_(2024_film)"),
    dict(id="premalu", title="Premalu", year=2024, runtime_min=156, genres=["Comedy", "Romance"], languages=["Malayalam"], countries=["India"], imdb=7.8, overview="A Hyderabad crush, a wedding, and two very different suitors.", themes=["romance", "comedy"], directors=["Girish A. D."], platforms=["JioHotstar"], poster_hue=330, wiki="Premalu"),
    dict(id="minnal-murali", title="Minnal Murali", year=2021, runtime_min=158, genres=["Action", "Comedy", "Fantasy", "Superhero"], languages=["Malayalam"], countries=["India"], imdb=7.8, overview="A tailor in a Kerala village is struck by lightning and becomes a reluctant hero.", themes=["superhero", "village"], directors=["Basil Joseph"], platforms=["Netflix"], poster_hue=48, wiki="Minnal_Murali"),
    dict(id="great-indian-kitchen", title="The Great Indian Kitchen", year=2021, runtime_min=100, genres=["Drama"], languages=["Malayalam"], countries=["India"], imdb=8.1, overview="A newlywed's life shrinks to a kitchen and a set of in-law rules.", themes=["patriarchy", "domestic"], directors=["Jeo Baby"], platforms=["Neestream"], poster_hue=28, wiki="The_Great_Indian_Kitchen"),
    dict(id="jallikattu-2019", title="Jallikattu", year=2019, runtime_min=91, genres=["Action", "Drama", "Thriller"], languages=["Malayalam"], countries=["India"], imdb=7.4, overview="A buffalo escapes a slaughter and a village turns feral overnight.", themes=["mob", "animal", "masculinity"], directors=["Lijo Jose Pellissery"], platforms=["Prime Video"], poster_hue=12, wiki="Jallikattu_(2019_film)"),
    dict(id="malik", title="Malik", year=2021, runtime_min=161, genres=["Crime", "Drama", "Thriller"], languages=["Malayalam"], countries=["India"], imdb=8.0, overview="A coastal godfather is hunted by the state that once used him.", themes=["politics", "coast", "rise and fall"], directors=["Mahesh Narayanan"], platforms=["Prime Video", "SonyLIV"], poster_hue=210, wiki="Malik_(2021_film)"),
    dict(id="2018-film", title="2018", year=2023, runtime_min=148, genres=["Drama", "Thriller"], languages=["Malayalam"], countries=["India"], imdb=8.3, overview="An ensemble survival story set during Kerala's 2018 floods.", themes=["flood", "ensemble", "true story"], directors=["Jude Anthany Joseph"], platforms=["Netflix", "JioHotstar"], poster_hue=200, wiki="2018_(film)"),
    dict(id="kannur-squad", title="Kannur Squad", year=2023, runtime_min=141, genres=["Crime", "Thriller", "Drama"], languages=["Malayalam"], countries=["India"], imdb=7.6, overview="A Kannur police squad chases a murder case across state lines.", themes=["investigation", "procedure"], directors=["Roby Varghese Raj"], platforms=["JioHotstar", "Netflix"], poster_hue=22, wiki="Kannur_Squad"),
    dict(id="anjaam-pathiraa", title="Anjaam Pathiraa", year=2020, runtime_min=144, genres=["Crime", "Thriller", "Mystery"], languages=["Malayalam"], countries=["India"], imdb=7.8, overview="A forensic psychologist profiles a killer targeting police officers.", themes=["serial killer", "forensics"], directors=["Midhun Manuel Thomas"], platforms=["Prime Video", "Netflix"], poster_hue=0, wiki="Anjaam_Pathiraa"),
    dict(id="ayyappanum-koshiyum", title="Ayyappanum Koshiyum", year=2020, runtime_min=175, genres=["Action", "Drama", "Thriller"], languages=["Malayalam"], countries=["India"], imdb=8.0, overview="An ego clash between a cop and an ex-serviceman in the high ranges.", themes=["ego", "class", "masculinity"], directors=["Sachy"], platforms=["Prime Video"], poster_hue=30, wiki="Ayyappanum_Koshiyum"),
    dict(id="bheeshma-parvam", title="Bheeshma Parvam", year=2022, runtime_min=164, genres=["Action", "Crime", "Drama"], languages=["Malayalam"], countries=["India"], imdb=7.6, overview="A Kochi family saga loosely drawn from the Mahabharata.", themes=["family", "godfather"], directors=["Amal Neerad"], platforms=["SonyLIV", "Netflix"], poster_hue=18, wiki="Bheeshma_Parvam"),
    dict(id="lucifer-2019", title="Lucifer", year=2019, runtime_min=174, genres=["Action", "Crime", "Drama", "Thriller"], languages=["Malayalam"], countries=["India"], imdb=7.5, overview="A political vacuum in Kerala after a chief minister's death.", themes=["politics", "power"], directors=["Prithviraj Sukumaran"], platforms=["Prime Video", "Netflix"], poster_hue=260, wiki="Lucifer_(2019_film)"),
    dict(id="manichitrathazhu", title="Manichitrathazhu", year=1993, runtime_min=169, genres=["Thriller", "Horror", "Drama", "Musical"], languages=["Malayalam"], countries=["India"], imdb=8.7, overview="A bride in a palace is haunted by a dancer's legend, and a psychiatrist arrives.", themes=["possession", "palace", "psychology"], directors=["Fazil"], platforms=["Prime Video"], poster_hue=15, wiki="Manichitrathazhu"),
    dict(id="bhool-bhulaiyaa", title="Bhool Bhulaiyaa", year=2007, runtime_min=159, genres=["Comedy", "Horror", "Thriller"], languages=["Hindi"], countries=["India"], imdb=7.4, overview="Hindi remake of Manichitrathazhu set in a palatial house in the north.", themes=["possession", "remake"], directors=["Priyadarshan"], platforms=["Netflix", "Prime Video"], poster_hue=16, tags=["Remake"], remake_of="Manichitrathazhu (1993, Malayalam)", wiki="Bhool_Bhulaiyaa"),
    dict(id="drishyam-2-ml", title="Drishyam 2", year=2021, runtime_min=152, genres=["Thriller", "Crime", "Drama"], languages=["Malayalam"], countries=["India"], imdb=8.4, overview="Years after the cover-up, a new investigation reopens Georgekutty's case.", themes=["alibi", "sequel", "police"], directors=["Jeethu Joseph"], platforms=["Prime Video", "JioHotstar"], poster_hue=140, wiki="Drishyam_2"),
    dict(id="drishyam-2-hi", title="Drishyam 2", year=2022, runtime_min=140, genres=["Thriller", "Crime", "Drama"], languages=["Hindi"], countries=["India"], imdb=8.2, overview="Hindi sequel-remake: Vijay Salgaonkar's six-year-old secret starts to leak.", themes=["alibi", "remake", "sequel"], directors=["Abhishek Pathak"], platforms=["Prime Video", "Netflix"], poster_hue=142, tags=["Remake"], remake_of="Drishyam 2 (2021, Malayalam)", wiki="Drishyam_2_(2022_film)"),
    dict(id="kingdom", title="Kingdom", year=2019, type="series", seasons=2, genres=["Horror", "Action", "Drama", "Thriller"], languages=["Korean"], countries=["South Korea"], imdb=8.3, overview="A crown prince faces a Joseon plague of the undead and a palace coup.", themes=["zombie", "palace", "period"], directors=["Kim Seong-hun"], platforms=["Netflix"], poster_hue=10, wiki="Kingdom_(South_Korean_TV_series)"),
    dict(id="hellbound", title="Hellbound", year=2021, type="series", seasons=2, genres=["Horror", "Drama", "Thriller", "Fantasy"], languages=["Korean"], countries=["South Korea"], imdb=6.6, overview="Angels decree damnation in public and a cult fills the vacuum.", themes=["cult", "faith", "spectacle"], directors=["Yeon Sang-ho"], platforms=["Netflix"], poster_hue=0, wiki="Hellbound_(TV_series)"),
    dict(id="the-glory", title="The Glory", year=2022, type="series", seasons=1, genres=["Thriller", "Drama", "Crime"], languages=["Korean"], countries=["South Korea"], imdb=8.1, overview="A woman spends decades building revenge on her high-school abusers.", themes=["revenge", "school", "class"], directors=["Ahn Gil-ho"], platforms=["Netflix"], poster_hue=350, wiki="The_Glory_(South_Korean_TV_series)"),
    dict(id="weak-hero", title="Weak Hero Class 1", year=2022, type="series", seasons=1, genres=["Action", "Drama", "Thriller"], languages=["Korean"], countries=["South Korea"], imdb=8.6, overview="A quiet transfer student uses brains and fists against school gangs.", themes=["school", "violence", "friendship"], directors=["Park Ran-hee"], platforms=["Wavve", "Netflix"], poster_hue=40, wiki="Weak_Hero"),
    dict(id="moving", title="Moving", year=2023, type="series", seasons=1, genres=["Action", "Drama", "Thriller", "Sci-Fi"], languages=["Korean"], countries=["South Korea"], imdb=8.4, overview="Superpowered parents try to hide their past from their children.", themes=["superpower", "family", "spies"], directors=["Park In-je"], platforms=["Disney+"], poster_hue=210, wiki="Moving_(South_Korean_TV_series)"),
    dict(id="extraordinary-attorney-woo", title="Extraordinary Attorney Woo", year=2022, type="series", seasons=1, genres=["Drama", "Comedy"], languages=["Korean"], countries=["South Korea"], imdb=8.6, overview="A brilliant autistic lawyer joins a top firm and takes odd cases.", themes=["law", "neurodiversity", "whales"], directors=["Yoo In-shik"], platforms=["Netflix"], poster_hue=200, wiki="Extraordinary_Attorney_Woo"),
    dict(id="crash-landing", title="Crash Landing on You", year=2019, type="series", seasons=1, genres=["Romance", "Drama", "Comedy"], languages=["Korean"], countries=["South Korea"], imdb=8.7, overview="A chaebol heiress paraglides into North Korea and a soldier hides her.", themes=["romance", "dmz", "class"], directors=["Lee Jeong-hyo"], platforms=["Netflix"], poster_hue=345, wiki="Crash_Landing_on_You"),
    dict(id="itaewon-class", title="Itaewon Class", year=2020, type="series", seasons=1, genres=["Drama", "Action"], languages=["Korean"], countries=["South Korea"], imdb=8.2, overview="An ex-con opens a bar and takes on a food conglomerate.", themes=["revenge", "found family", "business"], directors=["Kim Sung-yoon"], platforms=["Netflix"], poster_hue=18, wiki="Itaewon_Class"),
    dict(id="signal", title="Signal", year=2016, type="series", seasons=1, genres=["Crime", "Mystery", "Thriller", "Sci-Fi"], languages=["Korean"], countries=["South Korea"], imdb=8.5, overview="A walkie-talkie links present-day cops to a detective in 2000.", themes=["time", "cold case"], directors=["Kim Won-seok"], platforms=["Netflix", "Disney+"], poster_hue=220, wiki="Signal_(South_Korean_TV_series)"),
    dict(id="stranger-kr", title="Stranger", year=2017, type="series", seasons=2, genres=["Crime", "Mystery", "Thriller", "Drama"], languages=["Korean"], countries=["South Korea"], imdb=8.5, overview="A prosecutor who cannot feel and a cop who feels too much share a case.", themes=["prosecution", "corruption"], directors=["Ahn Gil-ho"], platforms=["Netflix"], poster_hue=30, wiki="Stranger_(TV_series)"),
    dict(id="the-chaser", title="The Chaser", year=2008, runtime_min=125, genres=["Crime", "Thriller", "Action"], languages=["Korean"], countries=["South Korea"], imdb=7.8, overview="A pimp realizes a client is a serial killer and races the police.", themes=["serial killer", "manhunt"], directors=["Na Hong-jin"], platforms=["Prime Video"], poster_hue=5, wiki="The_Chaser_(2008_film)"),
    dict(id="i-saw-the-devil", title="I Saw the Devil", year=2010, runtime_min=144, genres=["Thriller", "Crime", "Horror", "Action"], languages=["Korean"], countries=["South Korea"], imdb=7.8, overview="A secret agent plays a sadistic game of catch-and-release with a killer.", themes=["revenge", "cat and mouse"], directors=["Kim Jee-woon"], platforms=["Prime Video"], poster_hue=0, wiki="I_Saw_the_Devil"),
    dict(id="new-world-2013", title="New World", year=2013, runtime_min=134, genres=["Crime", "Action", "Thriller", "Drama"], languages=["Korean"], countries=["South Korea"], imdb=7.5, overview="An undercover cop is trapped between a crime syndicate and his handlers.", themes=["undercover", "loyalty"], directors=["Park Hoon-jung"], platforms=["Prime Video"], poster_hue=20, wiki="New_World_(2013_film)"),
    dict(id="joint-security-area", title="Joint Security Area", year=2000, runtime_min=110, genres=["Drama", "Thriller", "Mystery"], languages=["Korean"], countries=["South Korea"], imdb=7.7, overview="A shooting in the DMZ and two sides of a forbidden friendship.", themes=["dmz", "friendship"], directors=["Park Chan-wook"], platforms=["Max", "Prime Video"], poster_hue=70, wiki="Joint_Security_Area_(film)"),
    dict(id="your-name", title="Your Name", year=2016, runtime_min=106, genres=["Animation", "Drama", "Romance", "Fantasy"], languages=["Japanese"], countries=["Japan"], imdb=8.4, overview="Two teenagers swap bodies and chase a disaster across time.", themes=["body swap", "comet", "memory"], directors=["Makoto Shinkai"], platforms=["Netflix", "Prime Video"], poster_hue=200, wiki="Your_Name"),
    dict(id="spirited-away", title="Spirited Away", year=2001, runtime_min=125, genres=["Animation", "Adventure", "Family", "Fantasy"], languages=["Japanese"], countries=["Japan"], imdb=8.6, overview="A girl takes a job in a spirit bathhouse to free her parents.", themes=["spirits", "coming of age"], directors=["Hayao Miyazaki"], platforms=["Max", "Netflix"], poster_hue=15, wiki="Spirited_Away"),
    dict(id="princess-mononoke", title="Princess Mononoke", year=1997, runtime_min=134, genres=["Animation", "Adventure", "Fantasy"], languages=["Japanese"], countries=["Japan"], imdb=8.3, overview="A cursed prince walks into a war between forest gods and an iron town.", themes=["nature", "war"], directors=["Hayao Miyazaki"], platforms=["Max"], poster_hue=110, wiki="Princess_Mononoke"),
    dict(id="monster-koreeda", title="Monster", year=2023, runtime_min=126, genres=["Drama", "Mystery"], languages=["Japanese"], countries=["Japan"], imdb=7.9, overview="A mother, a teacher, and a principal tell three versions of a school incident.", themes=["perspective", "childhood"], directors=["Hirokazu Kore-eda"], platforms=["MUBI", "Prime Video"], poster_hue=48, wiki="Monster_(2023_film)"),
    dict(id="city-of-god", title="City of God", year=2002, runtime_min=130, genres=["Crime", "Drama"], languages=["Portuguese"], countries=["Brazil"], imdb=8.6, overview="Kids grow up inside Rio's City of God as drug wars rewrite the streets.", themes=["favela", "coming of age", "crime"], directors=["Fernando Meirelles"], platforms=["Max", "Prime Video"], poster_hue=18, wiki="City_of_God_(2002_film)"),
    dict(id="roma-already"),
    dict(id="amelie", title="Amélie", year=2001, runtime_min=122, genres=["Comedy", "Romance"], languages=["French"], countries=["France"], imdb=8.3, overview="A Montmartre waitress anonymously improves the lives around her.", themes=["whimsy", "paris"], directors=["Jean-Pierre Jeunet"], platforms=["Prime Video", "Max"], poster_hue=22, wiki="Amélie"),
    dict(id="intouchables", title="The Intouchables", year=2011, runtime_min=112, genres=["Comedy", "Drama", "Biography"], languages=["French"], countries=["France"], imdb=8.5, overview="A quadriplegic aristocrat hires a caregiver from the banlieue.", themes=["friendship", "class"], directors=["Olivier Nakache"], platforms=["Netflix", "Prime Video"], poster_hue=40, wiki="The_Intouchables"),
    dict(id="pans-labyrinth", title="Pan's Labyrinth", year=2006, runtime_min=118, genres=["Fantasy", "Drama", "War"], languages=["Spanish"], countries=["Mexico", "Spain"], imdb=8.2, overview="A girl in Franco-era Spain is offered three fairy-tale tasks.", themes=["fascism", "fairy tale"], directors=["Guillermo del Toro"], platforms=["Max"], poster_hue=30, wiki="Pan's_Labyrinth"),
    dict(id="city-of-god-dup"),
    dict(id="infernal-affairs", title="Infernal Affairs", year=2002, runtime_min=101, genres=["Crime", "Thriller", "Action", "Drama"], languages=["Cantonese"], countries=["Hong Kong"], imdb=8.0, overview="A cop undercover in a triad and a triad mole in the police hunt each other.", themes=["undercover", "identity"], directors=["Andrew Lau", "Alan Mak"], platforms=["Prime Video"], poster_hue=0, wiki="Infernal_Affairs"),
    dict(id="the-departed", title="The Departed", year=2006, runtime_min=151, genres=["Crime", "Thriller", "Drama"], languages=["English"], countries=["United States"], imdb=8.5, overview="Scorsese's Boston remake of Infernal Affairs.", themes=["undercover", "remake"], directors=["Martin Scorsese"], platforms=["Max", "Netflix"], poster_hue=8, tags=["Remake"], remake_of="Infernal Affairs (2002)", wiki="The_Departed"),
    dict(id="crouching-tiger", title="Crouching Tiger, Hidden Dragon", year=2000, runtime_min=120, genres=["Action", "Adventure", "Drama", "Fantasy"], languages=["Mandarin"], countries=["Taiwan", "China"], imdb=7.9, overview="Wudang swords, a stolen blade, and a warrior who wants out.", themes=["wuxia", "desire"], directors=["Ang Lee"], platforms=["Prime Video", "Max"], poster_hue=42, wiki="Crouching_Tiger,_Hidden_Dragon"),
    dict(id="ip-man", title="Ip Man", year=2008, runtime_min=106, genres=["Action", "Biography", "Drama"], languages=["Cantonese"], countries=["Hong Kong"], imdb=8.0, overview="Wing Chun master Ip Man in Japanese-occupied Foshan.", themes=["martial arts", "occupation"], directors=["Wilson Yip"], platforms=["Prime Video", "Netflix"], poster_hue=25, wiki="Ip_Man_(film)"),
    dict(id="lives-of-others", title="The Lives of Others", year=2006, runtime_min=137, genres=["Drama", "Thriller"], languages=["German"], countries=["Germany"], imdb=8.4, overview="A Stasi captain bugs a playwright and starts to care.", themes=["surveillance", "gdr"], directors=["Florian Henckel von Donnersmarck"], platforms=["Prime Video"], poster_hue=220, wiki="The_Lives_of_Others"),
    dict(id="run-lola-run", title="Run Lola Run", year=1998, runtime_min=81, genres=["Action", "Crime", "Thriller"], languages=["German"], countries=["Germany"], imdb=7.6, overview="Lola has twenty minutes to find 100,000 marks, three times.", themes=["time", "what if"], directors=["Tom Tykwer"], platforms=["Max", "Prime Video"], poster_hue=350, wiki="Run_Lola_Run"),
    dict(id="downfall", title="Downfall", year=2004, runtime_min=156, genres=["Biography", "Drama", "History", "War"], languages=["German"], countries=["Germany"], imdb=8.2, overview="Hitler's last days in the bunker, seen by a secretary.", themes=["war", "collapse"], directors=["Oliver Hirschbiegel"], platforms=["Prime Video"], poster_hue=40, wiki="Downfall_(2004_film)"),
    dict(id="girl-with-dragon-tattoo-sv", title="The Girl with the Dragon Tattoo", year=2009, runtime_min=152, genres=["Crime", "Drama", "Mystery", "Thriller"], languages=["Swedish"], countries=["Sweden"], imdb=7.8, overview="A journalist and a hacker reopen a 40-year-old disappearance.", themes=["investigation", "abuse"], directors=["Niels Arden Oplev"], platforms=["Prime Video", "Netflix"], poster_hue=0, wiki="The_Girl_with_the_Dragon_Tattoo_(2009_film)"),
    dict(id="let-the-right-one-in", title="Let the Right One In", year=2008, runtime_min=115, genres=["Drama", "Horror", "Romance"], languages=["Swedish"], countries=["Sweden"], imdb=7.8, overview="A bullied boy befriends the vampire next door.", themes=["vampire", "childhood", "snow"], directors=["Tomas Alfredson"], platforms=["Prime Video"], poster_hue=210, wiki="Let_the_Right_One_In_(film)"),
    dict(id="force-majeure", title="Force Majeure", year=2014, runtime_min=118, genres=["Comedy", "Drama"], languages=["Swedish"], countries=["Sweden"], imdb=7.2, overview="A controlled avalanche on a ski trip exposes a marriage.", themes=["cowardice", "family"], directors=["Ruben Östlund"], platforms=["MUBI", "Prime Video"], poster_hue=200, wiki="Force_Majeure_(film)"),
    dict(id="inception", title="Inception", year=2010, runtime_min=148, genres=["Action", "Sci-Fi", "Thriller"], languages=["English"], countries=["United States", "United Kingdom"], imdb=8.8, overview="A thief steals secrets from dreams and is offered one last inversion: inception.", themes=["dreams", "heist"], directors=["Christopher Nolan"], platforms=["Netflix", "Prime Video"], poster_hue=210, wiki="Inception"),
    dict(id="interstellar", title="Interstellar", year=2014, runtime_min=169, genres=["Adventure", "Drama", "Sci-Fi"], languages=["English"], countries=["United States", "United Kingdom"], imdb=8.7, overview="A pilot leaves a dying Earth through a wormhole to find another home.", themes=["space", "time", "family"], directors=["Christopher Nolan"], platforms=["Prime Video", "Paramount+"], poster_hue=30, wiki="Interstellar_(film)"),
    dict(id="whiplash", title="Whiplash", year=2014, runtime_min=106, genres=["Drama", "Music"], languages=["English"], countries=["United States"], imdb=8.5, overview="A jazz drummer is broken and rebuilt by a tyrannical teacher.", themes=["ambition", "abuse", "music"], directors=["Damien Chazelle"], platforms=["Netflix", "Max"], poster_hue=12, wiki="Whiplash_(2014_film)"),
    dict(id="mad-max-fury-road", title="Mad Max: Fury Road", year=2015, runtime_min=120, genres=["Action", "Adventure", "Sci-Fi"], languages=["English"], countries=["Australia", "United States"], imdb=8.1, overview="Furiosa flees a citadel with the wives of a warlord across the wasteland.", themes=["chase", "desert"], directors=["George Miller"], platforms=["Max"], poster_hue=22, wiki="Mad_Max:_Fury_Road"),
    dict(id="get-out", title="Get Out", year=2017, runtime_min=104, genres=["Horror", "Mystery", "Thriller"], languages=["English"], countries=["United States"], imdb=7.8, overview="A Black photographer meets his white girlfriend's family for a weekend.", themes=["race", "sunken place"], directors=["Jordan Peele"], platforms=["Prime Video", "Max"], poster_hue=90, wiki="Get_Out"),
    dict(id="arrival", title="Arrival", year=2016, runtime_min=116, genres=["Drama", "Sci-Fi", "Mystery"], languages=["English"], countries=["United States"], imdb=7.9, overview="A linguist is hired to talk to heptapods whose language rewires time.", themes=["language", "time", "grief"], directors=["Denis Villeneuve"], platforms=["Prime Video", "Netflix"], poster_hue=200, wiki="Arrival_(film)"),
    dict(id="blade-runner-2049", title="Blade Runner 2049", year=2017, runtime_min=164, genres=["Drama", "Sci-Fi", "Mystery"], languages=["English"], countries=["United States"], imdb=8.0, overview="A replicant blade runner uncovers a secret that could start a war.", themes=["identity", "future"], directors=["Denis Villeneuve"], platforms=["Netflix"], poster_hue=28, wiki="Blade_Runner_2049"),
    dict(id="no-country", title="No Country for Old Men", year=2007, runtime_min=122, genres=["Crime", "Drama", "Thriller"], languages=["English"], countries=["United States"], imdb=8.2, overview="A hunter takes a satchel of drug money and a killer follows.", themes=["fate", "violence"], directors=["Joel Coen", "Ethan Coen"], platforms=["Prime Video"], poster_hue=35, wiki="No_Country_for_Old_Men"),
    dict(id="social-network", title="The Social Network", year=2010, runtime_min=120, genres=["Biography", "Drama"], languages=["English"], countries=["United States"], imdb=7.8, overview="Harvard, depositions, and the founding of Facebook.", themes=["ambition", "betrayal"], directors=["David Fincher"], platforms=["Netflix"], poster_hue=210, wiki="The_Social_Network"),
    dict(id="grand-budapest", title="The Grand Budapest Hotel", year=2014, runtime_min=99, genres=["Adventure", "Comedy", "Crime"], languages=["English"], countries=["United States", "Germany"], imdb=8.1, overview="A concierge and a lobby boy are framed for murder in a fading Mitteleuropa.", themes=["hotel", "farce"], directors=["Wes Anderson"], platforms=["Disney+", "Hulu"], poster_hue=350, wiki="The_Grand_Budapest_Hotel"),
    dict(id="moonlight", title="Moonlight", year=2016, runtime_min=111, genres=["Drama"], languages=["English"], countries=["United States"], imdb=7.4, overview="Chiron grows up in three chapters in Miami.", themes=["identity", "queer", "coming of age"], directors=["Barry Jenkins"], platforms=["Netflix", "Prime Video"], poster_hue=220, wiki="Moonlight_(2016_film)"),
    dict(id="barbie", title="Barbie", year=2023, runtime_min=114, genres=["Adventure", "Comedy", "Fantasy"], languages=["English"], countries=["United States"], imdb=6.8, overview="Stereotypical Barbie leaves Barbieland for the real world.", themes=["feminism", "play"], directors=["Greta Gerwig"], platforms=["Max"], poster_hue=330, wiki="Barbie_(film)"),
    dict(id="poor-things", title="Poor Things", year=2023, runtime_min=141, genres=["Comedy", "Drama", "Romance", "Sci-Fi"], languages=["English"], countries=["Ireland", "United Kingdom"], imdb=7.8, overview="A reanimated woman with a child's brain tours a steampunk Europe.", themes=["feminist", "picaresque"], directors=["Yorgos Lanthimos"], platforms=["Hulu", "Disney+"], poster_hue=200, wiki="Poor_Things_(film)"),
    dict(id="the-substance", title="The Substance", year=2024, runtime_min=141, genres=["Horror", "Drama", "Sci-Fi"], languages=["English"], countries=["United Kingdom", "United States"], imdb=7.2, overview="An aging star takes a black-market serum that creates a younger self.", themes=["body", "fame", "split"], directors=["Coralie Fargeat"], platforms=["MUBI"], poster_hue=350, wiki="The_Substance"),
    dict(id="conclave", title="Conclave", year=2024, runtime_min=120, genres=["Drama", "Thriller"], languages=["English"], countries=["United Kingdom", "United States"], imdb=7.4, overview="Cardinals lock in to elect a pope and the secrets start leaking.", themes=["vatican", "power"], directors=["Edward Berger"], platforms=["Prime Video"], poster_hue=42, wiki="Conclave_(film)"),
    dict(id="anora", title="Anora", year=2024, runtime_min=139, genres=["Comedy", "Drama", "Romance"], languages=["English", "Russian"], countries=["United States"], imdb=7.6, overview="A Brooklyn stripper's whirlwind marriage to a Russian oligarch's son unravels.", themes=["class", "brooklyn"], directors=["Sean Baker"], platforms=["Hulu"], poster_hue=18, wiki="Anora"),
    dict(id="breaking-bad", title="Breaking Bad", year=2008, type="series", seasons=5, genres=["Crime", "Drama", "Thriller"], languages=["English"], countries=["United States"], imdb=9.5, overview="A chemistry teacher becomes a meth manufacturer.", themes=["crime", "family", "ego"], directors=["Vince Gilligan"], platforms=["Netflix"], poster_hue=80, wiki="Breaking_Bad"),
    dict(id="better-call-saul", title="Better Call Saul", year=2015, type="series", seasons=6, genres=["Crime", "Drama"], languages=["English"], countries=["United States"], imdb=9.0, overview="Jimmy McGill becomes Saul Goodman in the years before Walt.", themes=["law", "identity"], directors=["Vince Gilligan", "Peter Gould"], platforms=["Netflix"], poster_hue=40, wiki="Better_Call_Saul"),
    dict(id="the-wire", title="The Wire", year=2002, type="series", seasons=5, genres=["Crime", "Drama", "Thriller"], languages=["English"], countries=["United States"], imdb=9.3, overview="Baltimore through cops, corners, docks, schools, and the paper.", themes=["institutions", "city"], directors=["David Simon"], platforms=["Max"], poster_hue=25, wiki="The_Wire"),
    dict(id="succession", title="Succession", year=2018, type="series", seasons=4, genres=["Drama", "Comedy"], languages=["English"], countries=["United States"], imdb=8.8, overview="A media dynasty fights over who inherits the throne.", themes=["family", "power", "media"], directors=["Jesse Armstrong"], platforms=["Max"], poster_hue=210, wiki="Succession_(TV_series)"),
    dict(id="the-bear", title="The Bear", year=2022, type="series", seasons=3, genres=["Drama", "Comedy"], languages=["English"], countries=["United States"], imdb=8.5, overview="A fine-dining chef inherits a Chicago beef sandwich shop.", themes=["kitchen", "grief"], directors=["Christopher Storer"], platforms=["Hulu", "Disney+"], poster_hue=8, wiki="The_Bear_(TV_series)"),
    dict(id="slow-horses", title="Slow Horses", year=2022, type="series", seasons=4, genres=["Thriller", "Drama", "Spy"], languages=["English"], countries=["United Kingdom"], imdb=8.3, overview="MI5 rejects are dumped in Slough House under Jackson Lamb.", themes=["spy", "failure"], directors=["Will Smith"], platforms=["Apple TV+"], poster_hue=40, wiki="Slow_Horses"),
    dict(id="the-last-of-us", title="The Last of Us", year=2023, type="series", seasons=2, genres=["Action", "Adventure", "Drama", "Horror"], languages=["English"], countries=["United States"], imdb=8.7, overview="A smuggler escorts a girl across a fungal apocalypse.", themes=["outbreak", "found family"], directors=["Craig Mazin"], platforms=["Max"], poster_hue=70, wiki="The_Last_of_Us_(TV_series)"),
    dict(id="black-mirror", title="Black Mirror", year=2011, type="series", seasons=6, genres=["Sci-Fi", "Drama", "Thriller"], languages=["English"], countries=["United Kingdom"], imdb=8.7, overview="Anthology stories about technology going slightly too far.", themes=["tech", "dystopia"], directors=["Charlie Brooker"], platforms=["Netflix"], poster_hue=0, wiki="Black_Mirror"),
    dict(id="chernobyl", title="Chernobyl", year=2019, type="series", seasons=1, genres=["Drama", "History", "Thriller"], languages=["English"], countries=["United States", "United Kingdom"], imdb=9.3, overview="The 1986 disaster and the lies that made it worse.", themes=["disaster", "truth"], directors=["Craig Mazin"], platforms=["Max"], poster_hue=50, wiki="Chernobyl_(miniseries)"),
    dict(id="the-boys", title="The Boys", year=2019, type="series", seasons=4, genres=["Action", "Comedy", "Crime", "Sci-Fi"], languages=["English"], countries=["United States"], imdb=8.7, overview="Vigilantes take on corporate superheroes.", themes=["satire", "power"], directors=["Eric Kripke"], platforms=["Prime Video"], poster_hue=5, wiki="The_Boys_(TV_series)"),
    dict(id="andor", title="Andor", year=2022, type="series", seasons=2, genres=["Action", "Adventure", "Drama", "Sci-Fi"], languages=["English"], countries=["United States"], imdb=8.4, overview="Cassian Andor's path into the Rebellion.", themes=["fascism", "revolution"], directors=["Tony Gilroy"], platforms=["Disney+"], poster_hue=220, wiki="Andor_(TV_series)"),
    dict(id="shogun-already"),
    dict(id="pachinko", title="Pachinko", year=2022, type="series", seasons=2, genres=["Drama", "History"], languages=["Korean", "Japanese", "English"], countries=["United States", "South Korea"], imdb=8.4, overview="Four generations of a Korean family from Busan to Japan to America.", themes=["immigration", "family", "empire"], directors=["Soohyun Soze"], platforms=["Apple TV+"], poster_hue=20, wiki="Pachinko_(TV_series)"),
    dict(id="beef", title="Beef", year=2023, type="series", seasons=1, genres=["Comedy", "Drama"], languages=["English"], countries=["United States"], imdb=8.0, overview="A road-rage incident consumes two strangers' lives.", themes=["rage", "class"], directors=["Lee Sung Jin"], platforms=["Netflix"], poster_hue=12, wiki="Beef_(TV_series)"),
    dict(id="baby-reindeer", title="Baby Reindeer", year=2024, type="series", seasons=1, genres=["Drama", "Crime"], languages=["English"], countries=["United Kingdom"], imdb=7.7, overview="A comedian is stalked and the story of how they met keeps shifting.", themes=["stalking", "trauma", "true story"], directors=["Richard Gadd"], platforms=["Netflix"], poster_hue=30, wiki="Baby_Reindeer"),
    dict(id="ripley", title="Ripley", year=2024, type="series", seasons=1, genres=["Crime", "Drama", "Thriller"], languages=["English"], countries=["United States"], imdb=8.0, overview="Tom Ripley is sent to Italy to fetch a rich idler and stays.", themes=["identity", "italy", "noir"], directors=["Steven Zaillian"], platforms=["Netflix"], poster_hue=0, wiki="Ripley_(TV_series)"),
    dict(id="3-body-problem", title="3 Body Problem", year=2024, type="series", seasons=1, genres=["Drama", "Mystery", "Sci-Fi"], languages=["English"], countries=["United States"], imdb=7.5, overview="A countdown in a scientist's eyes and a game that is not a game.", themes=["aliens", "physics", "cultural revolution"], directors=["David Benioff"], platforms=["Netflix"], poster_hue=200, wiki="3_Body_Problem_(TV_series)"),
    dict(id="stranger-things", title="Stranger Things", year=2016, type="series", seasons=4, genres=["Drama", "Fantasy", "Horror", "Sci-Fi"], languages=["English"], countries=["United States"], imdb=8.7, overview="Hawkins, Indiana, a missing boy, and the Upside Down.", themes=["80s", "friendship", "monsters"], directors=["The Duffer Brothers"], platforms=["Netflix"], poster_hue=350, wiki="Stranger_Things"),
    dict(id="wednesday", title="Wednesday", year=2022, type="series", seasons=1, genres=["Comedy", "Crime", "Fantasy", "Mystery"], languages=["English"], countries=["United States"], imdb=8.0, overview="Wednesday Addams investigates murders at Nevermore Academy.", themes=["teen", "detective"], directors=["Tim Burton"], platforms=["Netflix"], poster_hue=0, wiki="Wednesday_(TV_series)"),
    dict(id="the-night-manager", title="The Night Manager", year=2016, type="series", seasons=1, genres=["Crime", "Drama", "Mystery", "Thriller", "Spy"], languages=["English"], countries=["United Kingdom"], imdb=8.0, overview="A hotelier is recruited to infiltrate an arms dealer's inner circle.", themes=["spy", "infiltration"], directors=["Susanne Bier"], platforms=["Prime Video", "BBC"], poster_hue=32, wiki="The_Night_Manager_(British_TV_series)"),
    dict(id="the-night-manager-hi", title="The Night Manager", year=2023, type="series", seasons=1, genres=["Crime", "Drama", "Thriller", "Spy"], languages=["Hindi"], countries=["India"], imdb=7.4, overview="Hindi remake: a hotel manager is used to get close to an arms dealer.", themes=["spy", "remake"], directors=["Priyanka Ghose"], platforms=["JioHotstar"], poster_hue=30, tags=["Remake"], remake_of="The Night Manager (2016, UK)", wiki="The_Night_Manager_(Indian_TV_series)"),
    dict(id="fight-club", title="Fight Club", year=1999, runtime_min=139, genres=["Drama", "Thriller"], languages=["English"], countries=["United States"], imdb=8.8, overview="An insomniac and a soap salesman start an underground fight club that becomes something else.", themes=["identity", "masculinity"], directors=["David Fincher"], platforms=["Prime Video", "Max"], poster_hue=20, cast=["Brad Pitt", "Edward Norton", "Helena Bonham Carter"], wiki="Fight_Club"),
    dict(id="se7en", title="Se7en", year=1995, runtime_min=127, genres=["Crime", "Mystery", "Thriller"], languages=["English"], countries=["United States"], imdb=8.6, overview="Two detectives hunt a killer who stages the seven deadly sins.", themes=["serial killer", "detective"], directors=["David Fincher"], platforms=["Max", "Prime Video"], poster_hue=0, cast=["Brad Pitt", "Morgan Freeman", "Gwyneth Paltrow"], wiki="Seven_(1995_film)"),
    dict(id="once-upon-hollywood", title="Once Upon a Time in Hollywood", year=2019, runtime_min=161, genres=["Comedy", "Drama"], languages=["English"], countries=["United States"], imdb=7.6, overview="A fading TV actor and his stunt double drift through 1969 Los Angeles.", themes=["hollywood", "1969"], directors=["Quentin Tarantino"], platforms=["Netflix", "Prime Video"], poster_hue=28, cast=["Leonardo DiCaprio", "Brad Pitt", "Margot Robbie"], wiki="Once_Upon_a_Time_in_Hollywood"),
    dict(id="oceans-eleven", title="Ocean's Eleven", year=2001, runtime_min=116, genres=["Crime", "Comedy", "Heist"], languages=["English"], countries=["United States"], imdb=7.7, overview="Danny Ocean recruits eleven specialists to rob three Las Vegas casinos.", themes=["heist", "vegas"], directors=["Steven Soderbergh"], platforms=["Max", "Netflix"], poster_hue=200, cast=["George Clooney", "Brad Pitt", "Julia Roberts"], wiki="Ocean's_Eleven_(2001_film)"),
    dict(id="inglourious-basterds", title="Inglourious Basterds", year=2009, runtime_min=153, genres=["Adventure", "Drama", "War"], languages=["English", "French", "German"], countries=["United States", "Germany"], imdb=8.4, overview="A Jewish-American commando unit and a French cinema plot to take down the Nazi high command.", themes=["war", "revenge"], directors=["Quentin Tarantino"], platforms=["Prime Video", "Netflix"], poster_hue=18, cast=["Brad Pitt", "Mélanie Laurent", "Christoph Waltz"], wiki="Inglourious_Basterds"),
    dict(id="moneyball", title="Moneyball", year=2011, runtime_min=133, genres=["Biography", "Drama", "Sport"], languages=["English"], countries=["United States"], imdb=7.6, overview="The A's general manager builds a playoff team with undervalued players and statistics.", themes=["baseball", "stats"], directors=["Bennett Miller"], platforms=["Netflix", "Prime Video"], poster_hue=40, cast=["Brad Pitt", "Jonah Hill", "Philip Seymour Hoffman"], wiki="Moneyball_(film)"),
    dict(id="world-war-z", title="World War Z", year=2013, runtime_min=116, genres=["Action", "Horror", "Sci-Fi"], languages=["English"], countries=["United States"], imdb=7.0, overview="A UN investigator races a global zombie pandemic.", themes=["zombie", "outbreak"], directors=["Marc Forster"], platforms=["Paramount+", "Prime Video"], poster_hue=70, cast=["Brad Pitt", "Mireille Enos"], wiki="World_War_Z_(film)"),
    dict(id="fury-2014", title="Fury", year=2014, runtime_min=134, genres=["Action", "Drama", "War"], languages=["English"], countries=["United States"], imdb=7.6, overview="A Sherman tank crew fights through Germany in the last months of World War II.", themes=["war", "tank"], directors=["David Ayer"], platforms=["Netflix", "Prime Video"], poster_hue=35, cast=["Brad Pitt", "Shia LaBeouf", "Logan Lerman"], wiki="Fury_(2014_film)"),
    dict(id="fifty-shades", title="Fifty Shades of Grey", year=2015, runtime_min=125, genres=["Drama", "Romance", "Thriller"], languages=["English"], countries=["United States"], imdb=4.2, overview="A student begins an affair with a wealthy man who wants a contract, not a relationship.", themes=["romance", "power"], directors=["Sam Taylor-Johnson"], platforms=["Netflix", "Prime Video"], poster_hue=0, cast=["Dakota Johnson", "Jamie Dornan"], wiki="Fifty_Shades_of_Grey_(film)"),
    dict(id="the-lost-daughter", title="The Lost Daughter", year=2021, runtime_min=121, genres=["Drama"], languages=["English"], countries=["United States", "United Kingdom"], imdb=6.7, overview="A scholar on a Greek holiday is pulled into memories of the mother she was.", themes=["motherhood", "memory"], directors=["Maggie Gyllenhaal"], platforms=["Netflix"], poster_hue=210, cast=["Olivia Colman", "Dakota Johnson", "Jessie Buckley"], wiki="The_Lost_Daughter_(film)"),
    dict(id="persuasion-2022", title="Persuasion", year=2022, runtime_min=107, genres=["Drama", "Romance"], languages=["English"], countries=["United States", "United Kingdom"], imdb=5.7, overview="Anne Elliot is persuaded out of an engagement, then he walks back into the room.", themes=["austen", "regret"], directors=["Carrie Cracknell"], platforms=["Netflix"], poster_hue=200, cast=["Dakota Johnson", "Cosmo Jarvis"], wiki="Persuasion_(2022_film)"),
    dict(id="cha-cha-real-smooth", title="Cha Cha Real Smooth", year=2022, runtime_min=107, genres=["Comedy", "Drama", "Romance"], languages=["English"], countries=["United States"], imdb=6.9, overview="A college graduate becomes a party starter and falls for a mom at the bar mitzvahs.", themes=["coming of age", "crush"], directors=["Cooper Raiff"], platforms=["Apple TV+"], poster_hue=330, cast=["Cooper Raiff", "Dakota Johnson"], wiki="Cha_Cha_Real_Smooth"),
    dict(id="materialists", title="Materialists", year=2025, runtime_min=116, genres=["Comedy", "Drama", "Romance"], languages=["English"], countries=["United States"], imdb=6.9, overview="A New York matchmaker is caught between a perfect client and an old love.", themes=["dating", "class"], directors=["Celine Song"], platforms=["Prime Video"], poster_hue=20, cast=["Dakota Johnson", "Pedro Pascal", "Chris Evans"], wiki="Materialists_(film)"),
    dict(id="madame-web", title="Madame Web", year=2024, runtime_min=116, genres=["Action", "Adventure", "Sci-Fi"], languages=["English"], countries=["United States"], imdb=3.8, overview="A paramedic who can see the future is pulled into protecting three young women.", themes=["superhero", "spider"], directors=["S. J. Clarkson"], platforms=["Netflix", "Prime Video"], poster_hue=350, cast=["Dakota Johnson", "Sydney Sweeney"], wiki="Madame_Web_(film)"),
    dict(id="legend-2015", title="Legend", year=2015, runtime_min=131, genres=["Biography", "Crime", "Drama"], languages=["English"], countries=["United Kingdom"], imdb=6.9, overview="Tom Hardy plays both Kray twins as they take over 1960s London.", themes=["twins", "gangsters", "dual role"], directors=["Brian Helgeland"], platforms=["Netflix", "Prime Video"], poster_hue=18, cast=["Tom Hardy", "Emily Browning"], dual_role_cast=["Tom Hardy"], wiki="Legend_(2015_film)"),
    dict(id="sacred-games-already"),
    dict(id="delhi-crime-already"),
    dict(id="amélie-dup"),
    dict(id="oldboy-already"),
    dict(id="memories-already"),
    dict(id="spirited-dup"),
    dict(id="city-of-god-2"),
    dict(id="portrait-already"),
    dict(id="anatomy-already"),
    dict(id="the-zone-already"),
    dict(id="oppenheimer-already"),
    dict(id="dune-already"),
    dict(id="parasite-already"),
    dict(id="squid-already"),
    dict(id="lupin-already"),
    dict(id="dark-already"),
    dict(id="money-heist-already"),
    dict(id="shogun-2"),
]


def _request(url: str) -> bytes:
    req = urllib.request.Request(url, headers={"User-Agent": UA, "Accept": "*/*"})
    with urllib.request.urlopen(req, timeout=25) as resp:
        return resp.read()


def summary(page: str) -> dict | None:
    url = "https://en.wikipedia.org/api/rest_v1/page/summary/" + urllib.parse.quote(page)
    for attempt in range(5):
        try:
            return json.loads(_request(url).decode("utf-8"))
        except urllib.error.HTTPError as exc:
            if exc.code in {404, 400}:
                return None
            if exc.code == 429 and attempt < 4:
                time.sleep(2.0 * (attempt + 1))
                continue
            raise


def fetch_poster(row: dict) -> None:
    wiki = row.pop("wiki", None)
    dest = POSTERS / f"{row['id']}.jpg"
    if dest.exists() and dest.stat().st_size > 1500:
        row["poster_url"] = f"/posters/{dest.name}"
        row["backdrop_url"] = row.get("backdrop_url") or f"/backdrops/{dest.name}"
        return
    if not wiki:
        return
    data = summary(wiki)
    if not data:
        print(f"  no wiki {row['id']} ({wiki})")
        return
    image = (data.get("originalimage") or {}).get("source") or (data.get("thumbnail") or {}).get("source")
    if not image:
        print(f"  no image {row['id']}")
        return
    payload = _request(image.split("?")[0])
    dest.parent.mkdir(parents=True, exist_ok=True)
    BACKDROPS.mkdir(parents=True, exist_ok=True)
    dest.write_bytes(payload)
    (BACKDROPS / dest.name).write_bytes(payload)
    row["poster_url"] = f"/posters/{dest.name}"
    row["backdrop_url"] = f"/backdrops/{dest.name}"
    print(f"  poster {row['title']}")


def normalize(row: dict) -> dict | None:
    if not row.get("id") or not row.get("title") or not row.get("year"):
        return None
    row.setdefault("type", "movie")
    row.setdefault("genres", [])
    row.setdefault("languages", [])
    row.setdefault("countries", [])
    row.setdefault("themes", [])
    row.setdefault("directors", [])
    row.setdefault("platforms", [])
    row.setdefault("tags", [])
    row.setdefault("cast", [])
    row.setdefault("dual_role_cast", [])
    row.setdefault("remake_of", None)
    row.setdefault("overview", "")
    row.setdefault("poster_hue", abs(hash(row["id"])) % 360)
    row.setdefault("imdb", None)
    row.setdefault("runtime_min", None)
    row.setdefault("seasons", None)
    return row


def main() -> None:
    catalog = json.loads(CATALOG.read_text(encoding="utf-8"))
    by_id = {row["id"]: row for row in catalog}
    wiki_by_id = {raw["id"]: raw["wiki"] for raw in ADDITIONS if raw.get("wiki")}
    added = 0
    for raw in ADDITIONS:
        row = normalize(dict(raw))
        if not row:
            continue
        if row["id"] in by_id:
            existing = by_id[row["id"]]
            if raw.get("cast") and not existing.get("cast"):
                existing["cast"] = list(raw["cast"])
            if not existing.get("poster_url") and wiki_by_id.get(row["id"]):
                existing["wiki"] = wiki_by_id[row["id"]]
                try:
                    fetch_poster(existing)
                except Exception as exc:  # noqa: BLE001
                    print(f"  fail {existing['id']}: {exc}")
                existing.pop("wiki", None)
                time.sleep(0.4)
            continue
        try:
            fetch_poster(row)
        except Exception as exc:  # noqa: BLE001
            print(f"  fail {row['id']}: {exc}")
            row.pop("wiki", None)
        row.pop("wiki", None)
        catalog.append(row)
        by_id[row["id"]] = row
        added += 1
        time.sleep(0.4)
    for row in catalog:
        row.setdefault("tags", [])
        row.setdefault("cast", [])
        row.setdefault("dual_role_cast", [])
        row.setdefault("remake_of", None)
        if row.get("platforms"):
            row["platforms"] = ["Wavve" if p == "Waves" else p for p in row["platforms"]]
    CATALOG.write_text(json.dumps(catalog, indent=2) + "\n", encoding="utf-8")
    print(f"added {added}; total {len(catalog)}")


if __name__ == "__main__":
    main()
