#!/usr/bin/env python3
"""Seed the OpenShelf catalog. Ratings/runtimes are approximate public figures for demo search."""

from __future__ import annotations

import json
from pathlib import Path

TITLES = [
    dict(id="parasite", title="Parasite", year=2019, runtime_min=132, type="movie", genres=["Thriller", "Drama", "Comedy"], languages=["Korean"], countries=["South Korea"], imdb=8.5, overview="A cash-strapped family infiltrates a wealthy household, and the two clans collide in a class-war thriller.", themes=["class", "infiltration", "dark comedy", "con"], directors=["Bong Joon-ho"], platforms=["Max", "Prime Video"], poster_hue=32),
    dict(id="the-call", title="The Call", year=2020, runtime_min=112, type="movie", genres=["Thriller", "Mystery", "Sci-Fi"], languages=["Korean"], countries=["South Korea"], imdb=7.1, overview="Two women in different times are linked by a mysterious telephone call that lets them rewrite each other's fates.", themes=["time", "phone", "revenge", "duality"], directors=["Lee Chung-hyun"], platforms=["Netflix"], poster_hue=345),
    dict(id="decision-to-leave", title="Decision to Leave", year=2022, runtime_min=138, type="movie", genres=["Thriller", "Romance", "Mystery", "Crime"], languages=["Korean"], countries=["South Korea"], imdb=7.3, overview="A detective investigating a mountain death becomes obsessed with the dead man's widow.", themes=["obsession", "investigation", "ambiguity"], directors=["Park Chan-wook"], platforms=["MUBI", "Prime Video"], poster_hue=210),
    dict(id="burning", title="Burning", year=2018, runtime_min=148, type="movie", genres=["Drama", "Mystery", "Thriller"], languages=["Korean"], countries=["South Korea"], imdb=7.5, overview="A delivery driver is drawn into a cryptic triangle after a childhood friend returns from Africa with a wealthy stranger.", themes=["jealousy", "class", "unreliable", "fire"], directors=["Lee Chang-dong"], platforms=["MUBI"], poster_hue=18),
    dict(id="joji", title="Joji", year=2021, runtime_min=113, type="movie", genres=["Thriller", "Crime", "Drama"], languages=["Malayalam"], countries=["India"], imdb=7.8, overview="In a patriarchal rubber-estate household, a resentful son plots against his father in a Macbeth-like slow burn.", themes=["family", "greed", "patriarchy", "crime"], directors=["Dileesh Pothan"], platforms=["Prime Video", "SonyLIV"], poster_hue=25),
    dict(id="badla", title="Badla", year=2019, runtime_min=118, type="movie", genres=["Thriller", "Crime", "Mystery"], languages=["Hindi"], countries=["India"], imdb=7.8, overview="Hindi remake of The Invisible Guest: a woman accused of murder hires a shrewd investigator whose questions cut both ways.", themes=["whodunit", "lawyer", "twist", "accusation", "remake"], directors=["Sujoy Ghosh"], platforms=["Netflix", "JioHotstar"], poster_hue=220, tags=["Remake"], remake_of="The Invisible Guest (2016)"),
    dict(id="andhadhun", title="Andhadhun", year=2018, runtime_min=139, type="movie", genres=["Thriller", "Crime", "Comedy"], languages=["Hindi"], countries=["India"], imdb=8.2, overview="A pianist pretending to be blind walks into a murder and has to keep the act going.", themes=["blind", "murder", "dark comedy", "cover-up"], directors=["Sriram Raghavan"], platforms=["Netflix", "Prime Video"], poster_hue=280),
    dict(id="kill-2024", title="Kill", year=2024, runtime_min=105, type="movie", genres=["Action", "Thriller"], languages=["Hindi"], countries=["India"], imdb=7.5, overview="Commandos trapped on a Mumbai-bound train fight a gang that has taken the passengers hostage.", themes=["train", "one night", "violence", "rescue"], directors=["Nikhil Nagesh Bhat"], platforms=["Netflix"], poster_hue=0),
    dict(id="drishyam-2013", title="Drishyam", year=2013, runtime_min=160, type="movie", genres=["Thriller", "Crime", "Drama"], languages=["Malayalam"], countries=["India"], imdb=8.3, overview="A cable-TV operator in a Kerala hillside town constructs an alibi after his family commits a crime.", themes=["alibi", "family", "police", "cover-up"], directors=["Jeethu Joseph"], platforms=["JioHotstar", "Prime Video"], poster_hue=140, tags=["Original"]),
    dict(id="drishyam-2015", title="Drishyam", year=2015, runtime_min=163, type="movie", genres=["Thriller", "Crime", "Drama"], languages=["Hindi"], countries=["India"], imdb=8.2, overview="Hindi remake of the 2013 Malayalam film: a family man builds a cover story after a crime at home.", themes=["alibi", "family", "police", "cover-up", "remake"], directors=["Nishikant Kamat"], platforms=["JioHotstar", "Prime Video", "Netflix"], poster_hue=145, tags=["Remake"], remake_of="Drishyam (2013, Malayalam)"),
    dict(id="kahaani", title="Kahaani", year=2012, runtime_min=122, type="movie", genres=["Thriller", "Mystery"], languages=["Hindi"], countries=["India"], imdb=8.1, overview="A pregnant woman searches Kolkata for a husband who may never have existed.", themes=["missing person", "identity", "city"], directors=["Sujoy Ghosh"], platforms=["Prime Video"], poster_hue=15),
    dict(id="les-miserables-2019", title="Les Misérables", year=2019, runtime_min=104, type="movie", genres=["Crime", "Drama", "Thriller"], languages=["French"], countries=["France"], imdb=7.6, overview="A newcomer joins an anti-crime brigade in the Paris suburbs as a single incident threatens to explode the district.", themes=["police", "banlieue", "tensions", "one day"], directors=["Ladj Ly"], platforms=["Prime Video"], poster_hue=8),
    dict(id="night-of-the-12th", title="The Night of the 12th", year=2022, runtime_min=114, type="movie", genres=["Crime", "Drama", "Mystery", "Thriller"], languages=["French"], countries=["France"], imdb=7.1, overview="Grenoble detectives open a murder file that refuses to close, and the investigation hollows them out.", themes=["unsolved", "investigation", "misogyny"], directors=["Dominik Moll"], platforms=["MUBI"], poster_hue=230),
    dict(id="november-2022", title="November", year=2022, runtime_min=105, type="movie", genres=["Thriller", "Crime", "Drama"], languages=["French"], countries=["France"], imdb=7.1, overview="Five days after the 2015 Paris attacks, an anti-terror unit races through informants, raids, and bad leads.", themes=["terrorism", "procedure", "manhunt"], directors=["Cédric Jimenez"], platforms=["Prime Video"], poster_hue=40),
    dict(id="anatomy-of-a-fall", title="Anatomy of a Fall", year=2023, runtime_min=151, type="movie", genres=["Thriller", "Crime", "Drama", "Mystery"], languages=["French", "English"], countries=["France"], imdb=7.7, overview="A writer is tried for her husband's death after he falls from their remote chalet.", themes=["courtroom", "marriage", "ambiguity"], directors=["Justine Triet"], platforms=["Hulu", "Prime Video"], poster_hue=48),
    dict(id="teachers-lounge", title="The Teachers' Lounge", year=2023, runtime_min=98, type="movie", genres=["Drama", "Thriller"], languages=["German"], countries=["Germany"], imdb=7.4, overview="A well-meaning teacher tries to catch a thief at school and watches the community tear itself apart.", themes=["school", "paranoia", "ethics"], directors=["İlker Çatak"], platforms=["Prime Video"], poster_hue=160),
    dict(id="dogman", title="Dogman", year=2018, runtime_min=103, type="movie", genres=["Crime", "Drama", "Thriller"], languages=["Italian"], countries=["Italy"], imdb=7.2, overview="A meek dog groomer in a coastal town is bullied by a local thug until the relationship snaps.", themes=["bullying", "dogs", "revenge"], directors=["Matteo Garrone"], platforms=["MUBI"], poster_hue=95),
    dict(id="riders-of-justice", title="Riders of Justice", year=2020, runtime_min=116, type="movie", genres=["Action", "Comedy", "Drama", "Thriller"], languages=["Danish"], countries=["Denmark"], imdb=7.5, overview="A soldier is told his wife's train death was chance, then a data nerd argues it was a hit, and a revenge plot begins.", themes=["revenge", "statistics", "grief", "gang"], directors=["Anders Thomas Jensen"], platforms=["Prime Video"], poster_hue=200),
    dict(id="the-guilty-2018", title="The Guilty", year=2018, runtime_min=85, type="movie", genres=["Thriller", "Crime", "Drama"], languages=["Danish"], countries=["Denmark"], imdb=7.5, overview="A demoted officer works an emergency hotline and tries to save a woman using only a phone.", themes=["one room", "phone", "rescue"], directors=["Gustav Möller"], platforms=["Netflix"], poster_hue=265),
    dict(id="another-round", title="Another Round", year=2020, runtime_min=117, type="movie", genres=["Comedy", "Drama"], languages=["Danish"], countries=["Denmark"], imdb=7.7, overview="Four teachers test a theory that a constant blood-alcohol level improves daily life.", themes=["alcohol", "friendship", "midlife"], directors=["Thomas Vinterberg"], platforms=["MUBI", "Prime Video"], poster_hue=42),
    dict(id="the-platform", title="The Platform", year=2019, runtime_min=94, type="movie", genres=["Horror", "Sci-Fi", "Thriller"], languages=["Spanish"], countries=["Spain"], imdb=7.0, overview="Prisoners on vertical levels share a descending food platform in a brutal social experiment.", themes=["class", "prison", "allegory"], directors=["Galder Gaztelu-Urrutia"], platforms=["Netflix"], poster_hue=12),
    dict(id="invisible-guest", title="The Invisible Guest", year=2016, runtime_min=106, type="movie", genres=["Thriller", "Mystery", "Crime"], languages=["Spanish"], countries=["Spain"], imdb=8.0, overview="A businessman accused of murder walks a lawyer through a story that keeps changing shape.", themes=["twist", "confession", "hotel"], directors=["Oriol Paulo"], platforms=["Netflix"], poster_hue=318),
    dict(id="below-zero", title="Below Zero", year=2021, runtime_min=106, type="movie", genres=["Action", "Thriller", "Crime"], languages=["Spanish"], countries=["Spain"], imdb=6.2, overview="A police van transporting prisoners is ambushed on an icy road at night.", themes=["snow", "hostage", "one night"], directors=["Lluís Quílez"], platforms=["Netflix"], poster_hue=198),
    dict(id="occupant", title="The Occupant", year=2020, runtime_min=103, type="movie", genres=["Thriller", "Drama"], languages=["Spanish"], countries=["Spain"], imdb=6.4, overview="A laid-off executive becomes obsessed with the family now living in his former apartment.", themes=["stalking", "class", "identity theft"], directors=["David Pastor", "Àlex Pastor"], platforms=["Netflix"], poster_hue=175),
    dict(id="society-of-the-snow", title="Society of the Snow", year=2023, runtime_min=144, type="movie", genres=["Drama", "Adventure", "Thriller"], languages=["Spanish"], countries=["Spain", "Uruguay"], imdb=7.8, overview="Uruguayan rugby players survive a Andes plane crash and face impossible choices.", themes=["survival", "andes", "true story"], directors=["J. A. Bayona"], platforms=["Netflix"], poster_hue=210),
    dict(id="roma", title="Roma", year=2018, runtime_min=135, type="movie", genres=["Drama"], languages=["Spanish", "Mixtec"], countries=["Mexico"], imdb=7.7, overview="A live-in housekeeper in 1970s Mexico City navigates work, love, and political unrest.", themes=["class", "domestic work", "memory"], directors=["Alfonso Cuarón"], platforms=["Netflix"], poster_hue=40),
    dict(id="wild-goose-lake", title="The Wild Goose Lake", year=2019, runtime_min=113, type="movie", genres=["Crime", "Noir", "Thriller"], languages=["Mandarin"], countries=["China"], imdb=7.1, overview="A gangster on the run through Wuhan's night lakes meets a woman who may be bait.", themes=["noir", "night", "gang"], directors=["Diao Yinan"], platforms=["MUBI"], poster_hue=185),
    dict(id="only-the-river-flows", title="Only the River Flows", year=2023, runtime_min=102, type="movie", genres=["Crime", "Mystery", "Noir", "Thriller"], languages=["Mandarin"], countries=["China"], imdb=7.0, overview="A 1990s small-town detective hunts a killer while the case and his mind start to flood.", themes=["investigation", "1990s", "unreliable"], directors=["Wei Shujun"], platforms=["MUBI"], poster_hue=55),
    dict(id="limbo-hk", title="Limbo", year=2021, runtime_min=118, type="movie", genres=["Crime", "Noir", "Thriller"], languages=["Cantonese"], countries=["Hong Kong"], imdb=7.2, overview="A veteran cop and a rookie hunt a serial killer through garbage-strewn Hong Kong streets.", themes=["serial killer", "grime", "mentorship"], directors=["Soai Cheang"], platforms=["Prime Video"], poster_hue=70),
    dict(id="shoplifters", title="Shoplifters", year=2018, runtime_min=121, type="movie", genres=["Drama", "Crime"], languages=["Japanese"], countries=["Japan"], imdb=7.9, overview="A found family on the margins of Tokyo survives by shoplifting until they take in a battered girl.", themes=["found family", "poverty", "secrets"], directors=["Hirokazu Kore-eda"], platforms=["MUBI", "Max"], poster_hue=28),
    dict(id="drive-my-car", title="Drive My Car", year=2021, runtime_min=179, type="movie", genres=["Drama"], languages=["Japanese"], countries=["Japan"], imdb=7.5, overview="A widowed theater director is assigned a driver while rehearsing Uncle Vanya in Hiroshima.", themes=["grief", "theater", "road"], directors=["Ryusuke Hamaguchi"], platforms=["Max", "MUBI"], poster_hue=10),
    dict(id="perfect-days", title="Perfect Days", year=2023, runtime_min=124, type="movie", genres=["Drama"], languages=["Japanese"], countries=["Japan"], imdb=7.9, overview="A Tokyo toilet cleaner builds a quiet life out of cassettes, trees, and routine.", themes=["routine", "solitude", "city"], directors=["Wim Wenders"], platforms=["MUBI"], poster_hue=125),
    dict(id="confessions-2010", title="Confessions", year=2010, runtime_min=106, type="movie", genres=["Thriller", "Drama", "Mystery"], languages=["Japanese"], countries=["Japan"], imdb=7.7, overview="A teacher tells her class she knows who killed her daughter, then the revenge lesson begins.", themes=["revenge", "school", "confession"], directors=["Tetsuya Nakashima"], platforms=["Prime Video"], poster_hue=300),
    dict(id="godzilla-minus-one", title="Godzilla Minus One", year=2023, runtime_min=125, type="movie", genres=["Action", "Drama", "Sci-Fi", "Thriller"], languages=["Japanese"], countries=["Japan"], imdb=7.7, overview="Postwar Japan faces Godzilla while a kamikaze survivor looks for a reason to live.", themes=["war", "monster", "guilt"], directors=["Takashi Yamazaki"], platforms=["Netflix"], poster_hue=90),
    dict(id="beasts-clawing", title="Beasts Clawing at Straws", year=2020, runtime_min=108, type="movie", genres=["Thriller", "Crime", "Comedy"], languages=["Korean"], countries=["South Korea"], imdb=7.0, overview="A bag of cash ricochets through desperate strangers whose plans all go wrong.", themes=["money", "ensemble", "coincidence"], directors=["Kim Yong-hoon"], platforms=["Prime Video"], poster_hue=33),
    dict(id="hard-hit", title="Hard Hit", year=2021, runtime_min=93, type="movie", genres=["Thriller", "Action", "Crime"], languages=["Korean"], countries=["South Korea"], imdb=6.6, overview="A banker gets a call: a bomb is under his seat, and he must follow instructions in real time.", themes=["car", "bomb", "one shot", "family"], directors=["Kim Chang-ju"], platforms=["Netflix"], poster_hue=0),
    dict(id="midnight-2021", title="Midnight", year=2021, runtime_min=103, type="movie", genres=["Thriller", "Crime"], languages=["Korean"], countries=["South Korea"], imdb=6.4, overview="A deaf woman is stalked through Seoul at night by a recently released killer.", themes=["night", "disability", "stalker"], directors=["Kwon Oh-seung"], platforms=["Netflix"], poster_hue=250),
    dict(id="gangster-cop-devil", title="The Gangster, the Cop, the Devil", year=2019, runtime_min=113, type="movie", genres=["Action", "Crime", "Thriller"], languages=["Korean"], countries=["South Korea"], imdb=6.9, overview="A crime boss survives a serial attacker and teams with a cop to hunt him.", themes=["alliance", "serial", "revenge"], directors=["Lee Won-tae"], platforms=["Prime Video"], poster_hue=5),
    dict(id="train-to-busan", title="Train to Busan", year=2016, runtime_min=118, type="movie", genres=["Horror", "Action", "Thriller"], languages=["Korean"], countries=["South Korea"], imdb=7.6, overview="A workaholic father and his daughter are trapped on a KTX as a zombie outbreak spreads car by car.", themes=["zombie", "train", "sacrifice"], directors=["Yeon Sang-ho"], platforms=["Prime Video", "Netflix"], poster_hue=2),
    dict(id="oldboy", title="Oldboy", year=2003, runtime_min=120, type="movie", genres=["Thriller", "Action", "Mystery", "Drama"], languages=["Korean"], countries=["South Korea"], imdb=8.3, overview="A man imprisoned for 15 years without explanation is released and given five days to find his captor.", themes=["revenge", "imprisonment", "twist"], directors=["Park Chan-wook"], platforms=["Max"], poster_hue=22),
    dict(id="man-from-nowhere", title="The Man from Nowhere", year=2010, runtime_min=119, type="movie", genres=["Action", "Thriller", "Crime"], languages=["Korean"], countries=["South Korea"], imdb=7.7, overview="A quiet pawnshop owner with a lethal past hunts the traffickers who kidnapped his young neighbor.", themes=["rescue", "violence", "loner"], directors=["Lee Jeong-beom"], platforms=["Prime Video"], poster_hue=0),
    dict(id="memories-of-murder", title="Memories of Murder", year=2003, runtime_min=132, type="movie", genres=["Crime", "Drama", "Mystery", "Thriller"], languages=["Korean"], countries=["South Korea"], imdb=8.1, overview="Rural detectives botch and brood through Korea's first serial-killer case in the 1980s.", themes=["serial killer", "incompetence", "history"], directors=["Bong Joon-ho"], platforms=["Max"], poster_hue=45),
    dict(id="handmaiden", title="The Handmaiden", year=2016, runtime_min=145, type="movie", genres=["Thriller", "Romance", "Drama", "Crime"], languages=["Korean", "Japanese"], countries=["South Korea"], imdb=8.1, overview="A pickpocket is hired as a maid in a con against a Japanese heiress, and the scheme has more layers than planned.", themes=["con", "desire", "colonial"], directors=["Park Chan-wook"], platforms=["Prime Video"], poster_hue=340),
    dict(id="squid-game", title="Squid Game", year=2021, runtime_min=None, type="series", seasons=2, genres=["Thriller", "Drama", "Action"], languages=["Korean"], countries=["South Korea"], imdb=8.0, overview="Broke contestants play deadly children's games for a giant cash prize.", themes=["debt", "games", "class"], directors=["Hwang Dong-hyuk"], platforms=["Netflix"], poster_hue=348),
    dict(id="my-name", title="My Name", year=2021, runtime_min=None, type="series", seasons=1, genres=["Action", "Crime", "Thriller"], languages=["Korean"], countries=["South Korea"], imdb=7.8, overview="A woman infiltrates the police to avenge her father, working both a cartel and the force.", themes=["undercover", "revenge", "identity"], directors=["Kim Jin-min"], platforms=["Netflix"], poster_hue=0),
    dict(id="dp", title="D.P.", year=2021, runtime_min=None, type="series", seasons=2, genres=["Drama", "Action", "Thriller"], languages=["Korean"], countries=["South Korea"], imdb=8.2, overview="Army deserter hunters chase conscripts while exposing abuse inside the barracks.", themes=["military", "abuse", "manhunt"], directors=["Han Jun-hee"], platforms=["Netflix"], poster_hue=70),
    dict(id="beyond-evil", title="Beyond Evil", year=2021, runtime_min=None, type="series", seasons=1, genres=["Crime", "Thriller", "Mystery"], languages=["Korean"], countries=["South Korea"], imdb=8.1, overview="Two policemen in a quiet town circle a serial-murder case in which either could be guilty.", themes=["cat and mouse", "unreliable", "small town"], directors=["Shim Na-yeon"], platforms=["Netflix"], poster_hue=155),
    dict(id="dark", title="Dark", year=2017, runtime_min=None, type="series", seasons=3, genres=["Mystery", "Sci-Fi", "Thriller", "Drama"], languages=["German"], countries=["Germany"], imdb=8.7, overview="Children vanish in a German town whose caves hide a knot of time travel and family crimes.", themes=["time travel", "caves", "family"], directors=["Baran bo Odar"], platforms=["Netflix"], poster_hue=260),
    dict(id="kleo", title="Kleo", year=2022, runtime_min=None, type="series", seasons=2, genres=["Action", "Thriller", "Comedy", "Spy"], languages=["German"], countries=["Germany"], imdb=7.6, overview="An East German assassin is betrayed at the Wall's fall and cuts a path west for answers.", themes=["spy", "1990s", "revenge"], directors=["Jano Ben Chaabane"], platforms=["Netflix"], poster_hue=330),
    dict(id="lupin", title="Lupin", year=2021, runtime_min=None, type="series", seasons=3, genres=["Crime", "Mystery", "Thriller", "Heist"], languages=["French"], countries=["France"], imdb=7.5, overview="A gentleman thief uses Arsène Lupin stories to avenge his father and fleece the rich.", themes=["heist", "gentleman thief", "paris"], directors=["Louis Leterrier"], platforms=["Netflix"], poster_hue=50),
    dict(id="money-heist", title="Money Heist", year=2017, runtime_min=None, type="series", seasons=5, genres=["Crime", "Thriller", "Heist", "Drama"], languages=["Spanish"], countries=["Spain"], imdb=8.2, overview="A mastermind gathers thieves to mint money inside the Royal Mint of Spain.", themes=["heist", "hostages", "resistance"], directors=["Álex Pina"], platforms=["Netflix"], poster_hue=8),
    dict(id="sacred-games", title="Sacred Games", year=2018, runtime_min=None, type="series", seasons=2, genres=["Crime", "Thriller", "Drama"], languages=["Hindi"], countries=["India"], imdb=8.5, overview="A Mumbai cop is warned the city will be destroyed in 25 days, pulling him into a gangster's past.", themes=["underworld", "prophecy", "corruption"], directors=["Anurag Kashyap", "Vikramaditya Motwane"], platforms=["Netflix"], poster_hue=16),
    dict(id="delhi-crime", title="Delhi Crime", year=2019, runtime_min=None, type="series", seasons=3, genres=["Crime", "Drama", "Thriller"], languages=["Hindi"], countries=["India"], imdb=8.5, overview="Delhi Police race to solve a horrific assault case while the city explodes in protest.", themes=["procedure", "true crime", "city"], directors=["Richie Mehta"], platforms=["Netflix"], poster_hue=20),
    dict(id="paatal-lok", title="Paatal Lok", year=2020, runtime_min=None, type="series", seasons=2, genres=["Crime", "Thriller", "Drama"], languages=["Hindi"], countries=["India"], imdb=8.1, overview="A cynic inspector catches four suspects in a botched hit and follows the case into India's underworld.", themes=["caste", "media", "investigation"], directors=["Avinash Arun"], platforms=["Prime Video"], poster_hue=30),
    dict(id="family-man", title="The Family Man", year=2019, runtime_min=None, type="series", seasons=2, genres=["Action", "Thriller", "Drama", "Spy"], languages=["Hindi"], countries=["India"], imdb=8.7, overview="A mid-level intelligence officer juggles suburban family life and national-security crises.", themes=["spy", "family", "terrorism"], directors=["Raj Nidimoru", "Krishna D.K."], platforms=["Prime Video"], poster_hue=205),
    dict(id="alice-in-borderland", title="Alice in Borderland", year=2020, runtime_min=None, type="series", seasons=3, genres=["Thriller", "Sci-Fi", "Action", "Mystery"], languages=["Japanese"], countries=["Japan"], imdb=7.7, overview="Tokyo empties overnight and remaining players must clear deadly games to extend their visas.", themes=["games", "survival", "empty city"], directors=["Shinsuke Sato"], platforms=["Netflix"], poster_hue=175),
    dict(id="shogun", title="Shōgun", year=2024, runtime_min=None, type="series", seasons=1, genres=["Drama", "History", "Adventure", "Thriller"], languages=["Japanese", "English"], countries=["United States", "Japan"], imdb=8.6, overview="An English sailor is pulled into a succession war among Japanese lords in 1600.", themes=["feudal", "politics", "culture clash"], directors=["Rachel Kondo", "Justin Marks"], platforms=["Hulu", "Disney+"], poster_hue=14),
    dict(id="gone-girl", title="Gone Girl", year=2014, runtime_min=149, type="movie", genres=["Thriller", "Mystery", "Crime", "Drama"], languages=["English"], countries=["United States"], imdb=8.1, overview="A husband's media nightmare begins when his wife vanishes on their anniversary.", themes=["media", "marriage", "unreliable"], directors=["David Fincher"], platforms=["Max", "Prime Video"], poster_hue=350),
    dict(id="prisoners", title="Prisoners", year=2013, runtime_min=153, type="movie", genres=["Thriller", "Crime", "Mystery", "Drama"], languages=["English"], countries=["United States"], imdb=8.1, overview="A father takes the law into his own hands after his daughter disappears on Thanksgiving.", themes=["kidnapping", "vigilante", "rain"], directors=["Denis Villeneuve"], platforms=["Max"], poster_hue=40),
    dict(id="zodiac", title="Zodiac", year=2007, runtime_min=157, type="movie", genres=["Crime", "Drama", "Mystery", "Thriller"], languages=["English"], countries=["United States"], imdb=7.7, overview="Cartoonist Robert Graysmith is consumed by the Zodiac killer's unsolved letters.", themes=["obsession", "true crime", "newspapers"], directors=["David Fincher"], platforms=["Max"], poster_hue=38),
    dict(id="nightcrawler", title="Nightcrawler", year=2014, runtime_min=117, type="movie", genres=["Crime", "Thriller", "Drama"], languages=["English"], countries=["United States"], imdb=7.8, overview="A driven loner films LA crime scenes for TV and starts manufacturing the footage.", themes=["media", "ambition", "night"], directors=["Dan Gilroy"], platforms=["Prime Video"], poster_hue=50),
    dict(id="sicario", title="Sicario", year=2015, runtime_min=121, type="movie", genres=["Action", "Crime", "Drama", "Thriller"], languages=["English", "Spanish"], countries=["United States"], imdb=7.7, overview="An FBI agent is attached to a CIA-backed team waging an extra-legal war on cartels.", themes=["cartel", "border", "moral gray"], directors=["Denis Villeneuve"], platforms=["Prime Video"], poster_hue=45),
    dict(id="knives-out", title="Knives Out", year=2019, runtime_min=130, type="movie", genres=["Mystery", "Comedy", "Crime"], languages=["English"], countries=["United States"], imdb=7.9, overview="A gentleman detective unpicks a wealthy family's story after a famous novelist dies.", themes=["whodunit", "family", "class"], directors=["Rian Johnson"], platforms=["Prime Video", "Netflix"], poster_hue=200),
    dict(id="dune-2021", title="Dune", year=2021, runtime_min=155, type="movie", genres=["Sci-Fi", "Adventure", "Drama"], languages=["English"], countries=["United States"], imdb=8.0, overview="Paul Atreides is sent to the desert planet Arrakis, sole source of the spice mélange.", themes=["empire", "desert", "prophecy"], directors=["Denis Villeneuve"], platforms=["Max", "Prime Video"], poster_hue=32),
    dict(id="spiderverse", title="Spider-Man: Across the Spider-Verse", year=2023, runtime_min=140, type="movie", genres=["Animation", "Action", "Adventure", "Sci-Fi"], languages=["English"], countries=["United States"], imdb=8.6, overview="Miles Morales is hunted across the multiverse by a league of Spider-People with a rigid code.", themes=["multiverse", "identity", "family"], directors=["Joaquim Dos Santos"], platforms=["Netflix"], poster_hue=200),
    dict(id="oppenheimer", title="Oppenheimer", year=2023, runtime_min=180, type="movie", genres=["Biography", "Drama", "History"], languages=["English"], countries=["United States"], imdb=8.3, overview="J. Robert Oppenheimer builds the atomic bomb and then lives with what he unleased.", themes=["science", "guilt", "politics"], directors=["Christopher Nolan"], platforms=["Prime Video", "JioHotstar"], poster_hue=22),
    dict(id="past-lives", title="Past Lives", year=2023, runtime_min=105, type="movie", genres=["Drama", "Romance"], languages=["Korean", "English"], countries=["United States", "South Korea"], imdb=7.8, overview="Childhood friends from Seoul reunite in New York two decades later and measure what-if.", themes=["immigration", "what if", "reunion"], directors=["Celine Song"], platforms=["Prime Video"], poster_hue=200),
    dict(id="zone-of-interest", title="The Zone of Interest", year=2023, runtime_min=105, type="movie", genres=["Drama", "History", "War"], languages=["German", "Polish"], countries=["United Kingdom", "United States", "Poland"], imdb=7.3, overview="A Nazi commandant's family tends a garden beside Auschwitz, treating horror as background noise.", themes=["banality", "complicity", "sound"], directors=["Jonathan Glazer"], platforms=["Max"], poster_hue=90),
    dict(id="all-quiet", title="All Quiet on the Western Front", year=2022, runtime_min=148, type="movie", genres=["War", "Action", "Drama"], languages=["German"], countries=["Germany"], imdb=7.8, overview="A German teenager enlists in 1917 and is ground down by the Western Front.", themes=["war", "disillusion", "youth"], directors=["Edward Berger"], platforms=["Netflix"], poster_hue=70),
    dict(id="close-2022", title="Close", year=2022, runtime_min=104, type="movie", genres=["Drama"], languages=["French", "Dutch"], countries=["Belgium", "France", "Netherlands"], imdb=7.8, overview="An intense friendship between two 13-year-old boys collapses after a summer of rumors.", themes=["adolescence", "friendship", "grief"], directors=["Lukas Dhont"], platforms=["Prime Video"], poster_hue=48),
    dict(id="worst-person", title="The Worst Person in the World", year=2021, runtime_min=128, type="movie", genres=["Comedy", "Drama", "Romance"], languages=["Norwegian"], countries=["Norway"], imdb=7.7, overview="Julie drifts through love, work, and Oslo while trying to decide who she is allowed to be.", themes=["coming of age", "romance", "city"], directors=["Joachim Trier"], platforms=["MUBI", "Prime Video"], poster_hue=10),
    dict(id="headhunters", title="Headhunters", year=2011, runtime_min=100, type="movie", genres=["Thriller", "Action", "Crime"], languages=["Norwegian"], countries=["Norway"], imdb=7.5, overview="A corporate headhunter who moonlights as an art thief steals from the wrong war veteran.", themes=["art theft", "cat and mouse", "identity"], directors=["Morten Tyldum"], platforms=["Prime Video"], poster_hue=0),
    dict(id="the-hunt-2012", title="The Hunt", year=2012, runtime_min=115, type="movie", genres=["Drama"], languages=["Danish"], countries=["Denmark"], imdb=8.3, overview="A kindergarten teacher is accused by a child, and a small town turns on him overnight.", themes=["accusation", "community", "innocence"], directors=["Thomas Vinterberg"], platforms=["MUBI"], poster_hue=35),
    dict(id="about-elly", title="About Elly", year=2009, runtime_min=119, type="movie", genres=["Drama", "Mystery", "Thriller"], languages=["Persian"], countries=["Iran"], imdb=7.9, overview="A seaside trip unravels when one guest disappears and the group's story starts to slip.", themes=["disappearance", "lies", "group"], directors=["Asghar Farhadi"], platforms=["MUBI"], poster_hue=200),
    dict(id="holy-spider", title="Holy Spider", year=2022, runtime_min=117, type="movie", genres=["Crime", "Thriller", "Drama"], languages=["Persian"], countries=["Denmark", "Germany", "France", "Sweden"], imdb=7.4, overview="A journalist hunts a serial killer of sex workers in Mashhad who claims divine mission.", themes=["serial killer", "journalism", "misogyny"], directors=["Ali Abbasi"], platforms=["MUBI"], poster_hue=0),
    dict(id="agent-of-happiness", title="The Beekeeper of Aleppo", year=0, runtime_min=0),  # placeholder skip
]

# remove invalid
TITLES = [t for t in TITLES if t.get("year") and t.get("title") and t.get("id") != "agent-of-happiness"]

MORE = [
    dict(id="a-separation", title="A Separation", year=2011, runtime_min=123, type="movie", genres=["Drama", "Thriller"], languages=["Persian"], countries=["Iran"], imdb=8.3, overview="A couple's divorce collides with a hired caretaker and a charge that neither family can contain.", themes=["class", "truth", "court"], directors=["Asghar Farhadi"], platforms=["Prime Video"], poster_hue=40),
    dict(id="capernaum", title="Capernaum", year=2018, runtime_min=126, type="movie", genres=["Drama"], languages=["Arabic"], countries=["Lebanon"], imdb=8.4, overview="A 12-year-old boy in Beirut sues his parents for the crime of giving him life.", themes=["poverty", "childhood", "court"], directors=["Nadine Labaki"], platforms=["Netflix"], poster_hue=28),
    dict(id="the-salesman", title="The Salesman", year=2016, runtime_min=125, type="movie", genres=["Drama", "Thriller"], languages=["Persian"], countries=["Iran"], imdb=7.7, overview="A couple staging Death of a Salesman is shaken when an assault in their new apartment demands a response.", themes=["revenge", "theater", "marriage"], directors=["Asghar Farhadi"], platforms=["Prime Video"], poster_hue=30),
    dict(id="portrait-lady", title="Portrait of a Lady on Fire", year=2019, runtime_min=120, type="movie", genres=["Drama", "Romance", "History"], languages=["French"], countries=["France"], imdb=8.1, overview="A painter is hired to secretly portrait a bride-to-be on a Breton island, and they fall in love.", themes=["gaze", "island", "forbidden"], directors=["Céline Sciamma"], platforms=["Hulu", "MUBI"], poster_hue=20),
    dict(id="titane", title="Titane", year=2021, runtime_min=108, type="movie", genres=["Horror", "Drama", "Sci-Fi"], languages=["French"], countries=["France"], imdb=6.6, overview="A wanted woman with a mysterious connection to metal hides in a fire station by impersonating a missing son.", themes=["body", "identity", "found family"], directors=["Julia Ducournau"], platforms=["Prime Video"], poster_hue=350),
    dict(id="raw-2016", title="Raw", year=2016, runtime_min=99, type="movie", genres=["Horror", "Drama"], languages=["French"], countries=["France", "Belgium"], imdb=6.7, overview="A vegetarian vet student goes through a hazing week that awakens a carnivorous craving.", themes=["cannibal", "coming of age", "campus"], directors=["Julia Ducournau"], platforms=["Prime Video"], poster_hue=0),
    dict(id="exhuma", title="Exhuma", year=2024, runtime_min=134, type="movie", genres=["Horror", "Mystery", "Thriller"], languages=["Korean"], countries=["South Korea"], imdb=6.9, overview="Shamans and a geomancer exhume a grave that should have stayed sealed.", themes=["shaman", "curse", "grave"], directors=["Jang Jae-hyun"], platforms=["Prime Video"], poster_hue=80),
    dict(id="exhuma-ok", title="The Wailing", year=2016, runtime_min=156, type="movie", genres=["Horror", "Mystery", "Thriller"], languages=["Korean"], countries=["South Korea"], imdb=7.4, overview="A policeman in a mountain village tries to stop a plague-like possession that may be a stranger's doing.", themes=["possession", "village", "doubt"], directors=["Na Hong-jin"], platforms=["Prime Video"], poster_hue=90),
    dict(id="minari", title="Minari", year=2020, runtime_min=115, type="movie", genres=["Drama"], languages=["Korean", "English"], countries=["United States"], imdb=7.4, overview="A Korean-American family moves to rural Arkansas in the 1980s to start a farm.", themes=["immigration", "family", "farm"], directors=["Lee Isaac Chung"], platforms=["Prime Video"], poster_hue=100),
    dict(id="broker", title="Broker", year=2022, runtime_min=129, type="movie", genres=["Drama", "Crime"], languages=["Korean"], countries=["South Korea"], imdb=7.1, overview="Two men who sell abandoned babies form an unexpected family with a mother who wants her child back.", themes=["found family", "crime", "road"], directors=["Hirokazu Kore-eda"], platforms=["Prime Video"], poster_hue=45),
    dict(id="broker-hunt", title="Hunt", year=2022, runtime_min=131, type="movie", genres=["Action", "Thriller", "Spy"], languages=["Korean"], countries=["South Korea"], imdb=6.8, overview="Two rival Korean intelligence chiefs hunt a North Korean mole inside their own agency.", themes=["spy", "mole", "1980s"], directors=["Lee Jung-jae"], platforms=["Prime Video"], poster_hue=15),
    dict(id="special-delivery", title="Special Delivery", year=2022, runtime_min=108, type="movie", genres=["Action", "Crime", "Thriller"], languages=["Korean"], countries=["South Korea"], imdb=6.8, overview="A driver who will deliver anything is hired to transport a child, then the city's gangs close in.", themes=["driver", "chase", "child"], directors=["Park Dae-min"], platforms=["Netflix"], poster_hue=8),
    dict(id="emergency-declaration", title="Emergency Declaration", year=2021, runtime_min=140, type="movie", genres=["Action", "Thriller", "Drama"], languages=["Korean"], countries=["South Korea"], imdb=6.8, overview="A plane is threatened with a biological attack and the ground crew must decide whether it can land.", themes=["airplane", "bio", "ensemble"], directors=["Han Jae-rim"], platforms=["Prime Video"], poster_hue=200),
    dict(id="nayattu", title="Nayattu", year=2021, runtime_min=121, type="movie", genres=["Thriller", "Crime", "Drama"], languages=["Malayalam"], countries=["India"], imdb=7.8, overview="Three cops go on the run after a political case is pinned on them.", themes=["manhunt", "caste", "police"], directors=["Martin Prakkat"], platforms=["Netflix", "JioHotstar"], poster_hue=40),
    dict(id="maa-2024", title="Maharaja", year=2024, runtime_min=141, type="movie", genres=["Thriller", "Crime", "Drama"], languages=["Tamil"], countries=["India"], imdb=8.4, overview="A barber reports a burglary to the police with a story that is not about what was stolen.", themes=["investigation", "grief", "twist"], directors=["Nithilan Saminathan"], platforms=["Netflix"], poster_hue=22),
    dict(id="vikram", title="Vikram", year=2022, runtime_min=174, type="movie", genres=["Action", "Thriller", "Crime"], languages=["Tamil"], countries=["India"], imdb=8.3, overview="A black-ops squad and a drug syndicate collide after a retired cop is apparently killed.", themes=["undercover", "drugs", "ensemble"], directors=["Lokesh Kanagaraj"], platforms=["Prime Video", "Netflix"], poster_hue=0),
    dict(id="kaithi", title="Kaithi", year=2019, runtime_min=145, type="movie", genres=["Action", "Thriller", "Crime"], languages=["Tamil"], countries=["India"], imdb=8.4, overview="An ex-con must transport drunken cops to a station before a drug cartel storms it before dawn.", themes=["one night", "car", "redemption"], directors=["Lokesh Kanagaraj"], platforms=["Netflix"], poster_hue=25),
    dict(id="kumbalangi", title="Kumbalangi Nights", year=2019, runtime_min=114, type="movie", genres=["Drama", "Comedy", "Romance"], languages=["Malayalam"], countries=["India"], imdb=8.1, overview="Four brothers in a fishing village learn how to live together after a new fiancé enters the house.", themes=["brothers", "masculinity", "village"], directors=["Madhu C. Narayanan"], platforms=["Prime Video"], poster_hue=190),
    dict(id="manjummel", title="Manjummel Boys", year=2024, runtime_min=135, type="movie", genres=["Adventure", "Drama", "Thriller"], languages=["Malayalam"], countries=["India"], imdb=8.2, overview="Friends on a trip to Kodaikanal must rescue one of their own from Guna Caves.", themes=["friendship", "rescue", "true story"], directors=["Chidambaram"], platforms=["JioHotstar"], poster_hue=160),
    dict(id="kishkindha", title="Kishkindha Kaandam", year=2024, runtime_min=125, type="movie", genres=["Mystery", "Thriller", "Drama"], languages=["Malayalam"], countries=["India"], imdb=8.1, overview="A forest-range family and a troop of monkeys sit on top of a buried secret.", themes=["forest", "memory", "family"], directors=["Raghunath Paleri"], platforms=["JioHotstar"], poster_hue=110),
    dict(id="bramayugam", title="Bramayugam", year=2024, runtime_min=139, type="movie", genres=["Horror", "Thriller", "Drama", "History"], languages=["Malayalam"], countries=["India"], imdb=8.2, overview="A folk singer takes shelter in a mansion where a mysterious master plays games with time and caste.", themes=["folklore", "power", "monochrome"], directors=["Rahul Sadasivan"], platforms=["SonyLIV"], poster_hue=40),
    dict(id="super-deluxe", title="Super Deluxe", year=2019, runtime_min=176, type="movie", genres=["Drama", "Crime", "Comedy", "Thriller"], languages=["Tamil"], countries=["India"], imdb=8.2, overview="Intersecting Chennai stories involving a porn CD, a missing husband, and a transgender parent.", themes=["ensemble", "morality", "city"], directors=["Thiagarajan Kumararaja"], platforms=["Netflix"], poster_hue=320),
    dict(id="joker-2019", title="Joker", year=2019, runtime_min=122, type="movie", genres=["Crime", "Drama", "Thriller"], languages=["English"], countries=["United States"], imdb=8.4, overview="A failed clown and party comic unravels in a crumbling Gotham and becomes a symbol of riot.", themes=["mental health", "class", "origin"], directors=["Todd Phillips"], platforms=["Max"], poster_hue=48),
    dict(id="the-batman", title="The Batman", year=2022, runtime_min=176, type="movie", genres=["Action", "Crime", "Drama", "Mystery"], languages=["English"], countries=["United States"], imdb=7.8, overview="A young Batman follows a Riddler killing spree into Gotham's elite and his own family myth.", themes=["detective", "noir", "corruption"], directors=["Matt Reeves"], platforms=["Max"], poster_hue=210),
    dict(id="everything-everywhere", title="Everything Everywhere All at Once", year=2022, runtime_min=139, type="movie", genres=["Action", "Adventure", "Comedy", "Sci-Fi"], languages=["English", "Mandarin"], countries=["United States"], imdb=7.8, overview="A laundromat owner is pulled into a multiverse fight that is really about her daughter.", themes=["multiverse", "family", "taxes"], directors=["Daniel Kwan", "Daniel Scheinert"], platforms=["Prime Video", "Netflix"], poster_hue=300),
    dict(id="banshees", title="The Banshees of Inisherin", year=2022, runtime_min=114, type="movie", genres=["Comedy", "Drama"], languages=["English"], countries=["Ireland", "United Kingdom"], imdb=7.7, overview="On a Civil War-era island, a fiddler abruptly ends a friendship and the cut keeps deepening.", themes=["friendship", "isolation", "pride"], directors=["Martin McDonagh"], platforms=["Prime Video", "Hulu"], poster_hue=200),
    dict(id="aftersun", title="Aftersun", year=2022, runtime_min=102, type="movie", genres=["Drama"], languages=["English"], countries=["United Kingdom"], imdb=7.6, overview="A woman remembers a 1990s holiday with her young father at a Turkish resort.", themes=["memory", "fatherhood", "holiday"], directors=["Charlotte Wells"], platforms=["Prime Video"], poster_hue=195),
    dict(id="tár", title="TÁR", year=2022, runtime_min=158, type="movie", genres=["Drama", "Music"], languages=["English", "German"], countries=["United States"], imdb=7.4, overview="A famous conductor's control of her orchestra and her image begins to slip.", themes=["power", "cancel", "music"], directors=["Todd Field"], platforms=["Max"], poster_hue=0),
    dict(id="triangle-sadness", title="Triangle of Sadness", year=2022, runtime_min=147, type="movie", genres=["Comedy", "Drama"], languages=["English", "Swedish"], countries=["Sweden", "Germany", "France"], imdb=7.3, overview="A luxury cruise for models and oligarchs capsizes and the hierarchy flips on an island.", themes=["class", "satire", "yacht"], directors=["Ruben Östlund"], platforms=["Hulu", "Prime Video"], poster_hue=180),
]

def clean(row: dict) -> dict | None:
    if not row.get("title") or not row.get("year") or row.get("title") == "skip":
        return None
    row.setdefault("type", "movie")
    row.setdefault("genres", [])
    row.setdefault("languages", [])
    row.setdefault("countries", [])
    row.setdefault("themes", [])
    row.setdefault("directors", [])
    row.setdefault("platforms", [])
    row.setdefault("overview", "")
    row.setdefault("poster_hue", hash(row["id"]) % 360)
    row.setdefault("imdb", None)
    row.setdefault("tags", [])
    row.setdefault("remake_of", None)
    return row

records = []
seen = set()
for row in TITLES + MORE:
    item = clean(row)
    if not item or item["id"] in seen:
        continue
    seen.add(item["id"])
    records.append(item)

out = Path(__file__).resolve().parent / "data" / "catalog.json"
out.parent.mkdir(parents=True, exist_ok=True)
out.write_text(json.dumps(records, indent=2) + "\n", encoding="utf-8")
print(f"Wrote {len(records)} titles to {out}")
